= Release 7.6
16 Jul 2015


== Important changes

The "timetables" view has been removed from this release. This view was
not well optimised for speed and the way it displayed all sessions from
all classes in one big view wasn't terribly useful. The poor performance
of this view was giving new users a bad impression, where there are
better ways to show a timetable from site, room, class, course, student
or tutor views. We'll restore this view once we have a more useful
interface designed.

== Major features

=== User defined payment types

onCourse now allows you to add your own type of payment methods, for
example, VET FEE HELP, B-Pay or PayPal. You can also edit any existing
payment type that is included in onCourse, or remove a payment type that
you don't allow at your organisation e.g. cheque, provided you have
never taken any payments by that method.

=== Banking window restructure

The new banking window allows you to see all payment in and out
transactions grouped together on their banking date, including those
banked automatically such as credit card and EFTPOS. This will assist
with reconciliation process, as well as allow you to easily locate and
edit the banking dates of transactions such as EFT/direct deposit. To
access this window from the top menu by clicking on Financial ->
Banking. You can manually bank money from this window by clicking on the
'+' icon inside the banking list view. Alternatively, the 'Deposit
banking' window can still be accessed in the 'Accounts' tab of the
dashboard.

=== Transfer enrolment wizard

A transfer enrolment process has been added to the enrolment window cog
wheel function. This is similar to the 'cancel enrolment' process with
the addition of opening Quick Enrol at the end of the process, pre
loaded with the student, payer and course details, allowing you to make
a speedy transfer of the student to another class.

=== Reports and scripts

* Update all class roll reports that include the tutor names to use a
consistent layout so tutor names display correctly. Custom rolls have
also been updated and will be distributed directly `#25042`
* A new report has been added to show the detail of the enrolments which
have taken up a discount offer, called Discounts Take Up. This report
can be printed from the discount window, and groups by each discount
type each class and its enrolments from the date range entered in the
report runner. `#22885`
* An optional notification section for the "USI reminder
script":https://github.com/ari/oncourse-scripts/blob/master/scripts/send-usi-reminder.groovy
has been added, to alert a manager to the number of students emailed
each week. You can auto update your script using the button inside
onCourse, or manually by adding to the end:
+
[source,groovy]
----
  smtp {
    from preference.email.admin
    subject 'USI reminder email notification'
    to preference.email.admin
    content "A USI reminder was sent to ${enrolmentsWithoutUsi.size()} students enrolled in VET classes who have not supplied their USI."
  }

----
+
You can manually change your script from preference.email.admin to the
actual email address of your choice.`#24396`
* Custom fields in reports can now be easily accessed using syntax like
this: `$F{contact}.passportNumber` or if the field name contains spaces
like this `$F{contact}.customFieldValuehow did you hear")`.

== Minor features

* Membership expiry date is now editable during the Quick Enrol sales
process for the membership. This allows you to override the
automatically set date (based on the membership type preferences) to
another date of your choice.`#24089`
* Overdue column has been added to the invoice list view window to show
the amount of the invoice that is currently overdue for payment. This is
of particular use to invoices under payment plan agreements. `#24307`
* 'empty' and 'is not empty' search options have been added to all
onCourse advanced search fields, allowing you to search for example for
students who have a USI, rather than a specific USI `#24874`
* Add 'debtors account code' to advanced search options for invoice
window`#25114`
* If you use the cogwheel to 'Show courses on web site' in the course
list', and the course status was set to 'disabled', the status will now
be changed to 'enabled and visible online' `#25359`

== Fixes

* Allow private classes and traineeships to be marked as self paced on
creation `#25008`
* Allow copy and paste in search fields `#25029`
* Fix to the layout of the payment in and payment out window defaults so
fields are not truncated from view `#25036`
* Students TFNs were being cleared from their record when it was opened
in Quick Enrol. This has has been fixed. `#25116`
* Any 'Special Needs' notations made on the Documents tab are not being
retained after saving and closing. This has has been fixed. `#25178`
* Students that have no active enrolments are not displayed under
'students currently enrolled' filter `#19074`
* Apply rounding options to final price instead of just discount value .
This will correct some 1c rounding issues that may show on purchases
which have GST applied.`#24133, #25094, #25059`
* Fix to discount window where save process could fail if classes are
added before a discount name `#25269`
* Fix to the payment out post processing process to ensure the refund
advice email is sent where enabled by the corresponding script `#10073`
* Fix to the voucher expiry job to ensure that vouchers where the
purchase price has been modified expire correctly. Old records that did
not correctly expire will be corrected as part of the upgrade process
`#25102`
