
= Release 119
17 Apr. 2023

We're excited to announce onCourse update 119, which includes several quality-of-life improvements and bug fixes. From visual changes to 2FA to adding the ability to bulk delete Waiting Lists, we've made it easier to navigate and use onCourse while addressing various issues reported by our users. These changes are aimed at enhancing your overall experience and make using onCourse more enjoyable. We always appreciate your feedback and support, and remain committed to continually improving our product.

=== Major fixes
* Fixed an issue where contacts created through the checkout could not be enrolled in classes `OD-17945`

=== Minor features
* Added a new bulk delete function to clear old waiting list records `OD-18023`
* Refined the visualisation of our 2FA implementation `OD-17946`
* Improved the Share menu by adding a way to clear the preview from an item and changing the default setting for the 'create preview' checkbox to 'off' `OD-17899`
* Added a new feature that enables customers to manually execute a script on invoices `OD-17844`
* Improved visibility with the relationship visualiser function `OD-17716`
* The class budget graph more accurately represents projected and real data `OD-16189`
* Added a new error message when sending a message to a contact with an "undeliverable" email address `OD-17951`

=== Minor fixes
* Fixed an issue where opening some classes would freeze the browser `OD-18043`
* Resolved a problem where duplicated exports would prompt an error when attempting to save `OD-18026`
* Rectified an issue where timetables were set as a different timezone then the system default `OD-18025`
* Fixed a visual error when adding tags to documents linked to a course `OD-17988`
* Patched a bug that prevented relations from being added to contacts `OD-17987`
* Fixed an issue where the number of students related to enrolments was listed incorrectly `OD-17949`
* Made middle names no longer mandatory when adding a relationship to a contact `OD-17924`
* Addressed an issue where bulk updating a session time would not save correctly `OD-17388`
