= Release 7.1
15 Apr 2015


== Major features

=== USI validation improvements

Once as USI has been validated, the student contact details for First
Name, Last Name and Date of Birth, along with the USI lock for editing.
When the student advises you they have changed their details with the
USI Agency, a new option allows you to unlock the record, forcing a
re-validation attempt with the new details.

A middle name field has also been added to contact records, allowing you
to store this data separately from first names. Middle names stored with
first names were making USI validation attempts fail.

A new type of class roll has also been added, showing if the student has
supplied a USI and if that USI has passed validation or not, so your
tutors can assist with the data collection process.

The USI verification process also now runs during the Quick Enrol
creation, so if you choose to add a student's USI to their record while
processing an enrolment or other purchase for them, the SOAP
verification will run the background.

The student merge process also only allows the verified USI data to be
chosen when merging two students and will not allow two students with
different USIs that have been validated to be merged. Students with the
same validated USI can be merged.

The USI portal link sent out in the student enrolment confirmation and
the USI reminder email has also been changed to a 7 day expiry, up from
3 days. You can also manually adjust this to a longer or shorter period
yourself by editing your email templates.

=== Two factor authentication

An optional added layer of security for users accessing onCourse cloud
instances in particular, but also useful for locally hosted onCourse
servers with VPN access enabled.

Two factor authentication requires both a password and a device
generated one time token, so if a computer used to access onCourse has
it's security comprised, for example, has a malicious keylogger
installed, your onCourse database access will remain secure. You may use
a similar process when logging into internet banking. For two factor
authentication log in access to be compromised, someone would need to
have the onCourse users phone and also know their password.

An application installed on each onCourse users smart phone, such as
https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=en[Google
Authenticator] will generate the one time token required to successfully
log in. The token has a limited life span and will automatically update
every 30 seconds inside the app.

Two factor authentication is available for all onCourse users at no
cost. There is no cost to install the software on your smart phone. More
information about how to enable this feature is in the onCourse manual
Users and Authentication Chapter

=== Notes field layout

All notes fields are now multiple part records consisting of the note,
with the time and dates and user details of who created it. This change
has been made to the contact, course, class, site, room, application and
invoice records.

Admin users can edit and/or delete existing notes. All other user types
can create new notes only, but not change existing notes. Further access
control options will be added in the next release of onCourse.

=== Enrolment tab redesign

New fields have been added to allow for changed AVETMISS reporting
requirements, as well as an overall layout refresh. Additional fields
have been added to the enrolment level, particularly to cater for NSW
Smart and Skilled reporting that include VET in Schools flag, Purchasing
Contract Identifier (NSW Commitment ID), Outcome Identifier – Training
Organisation, Associated Course Identifier (SA – SACE Student ID) and
Funding source – State.

For some of these fields, such as the Purchasing Contract Identifier
(NSW Commitment ID) you can set the value at the class level, enrolment
level or outcome level. Values set at a higher level will automatically
export at the lower level, except where a different value is set. For
example, you can set a funding source value at the class that applies to
all enrolments and outcomes, but if one student is funded under a
different arrangement, you can set that funding source in their
enrolment only.

=== AVETMISS exports update for NSW Smart & Skilled, NSW OLiV, VIC and SA

Two new AVETMISS export flavours – NSW Smart & Skilled and NSW OLiV have
been added. The previous NSW DET option is still available and is
unchanged as RTOs complete reporting for 2014 data.

The new Smart & Skilled export standard includes special rules such as
exporting Outcome Status – National as blank for all outcomes which have
not yet commenced (any outcome with a start date after the day you run
the export).

Victorian and South Australian specific fields have been added to
onCourse and the AVETMISS export options have been updated in line with
the 2015 export formats.

Updated AVETMISS reporting information is available in the onCourse
manual AVETMISS chapter

== Minor features

* Addition of the voucher redemption value in Quick Enrol voucher sales
process to make it clear of the difference between the voucher sale cost
and voucher redemption value `#20999`
* Remember the last used location for attaching files, to avoid having
to repetitively navigate through folder structures `#22104`
* Added per unit wage type to tutor role preferences `#22967`
* Removed unnecessary UI validation requiring the onCourse user to set
RPL outcomes to delivery type 'not set'. The AVETMISS export process
sets this value as standard whenever an RPL outcome is encountered
during export `#22612`
* Add additional access control options for products, contact relation
types, scripts and templates `#22412`
* Add selection of background template option to the Banking Report
print process `#22676`
* Add new feature for scripts to include 'tagged with' options `#23565`
* Added new fields in the VET tab of a student record called "Client
Industry of Employment (VIC)" and "Client Occupation Identifier (VIC)"
`#23885`
* Add find related enrolments to the discount cogwheel option, to locate
all enrolments that used a discount `#23417`
* Printing of all class rolls now includes electronically completed
marking results – Y for Yes – attended, N for No – absent/not attended.
Sessions with no electronic mark continue to print as a blank space so
they can be completed by hand `#23627`
* Addition of two fields to the preferences window next to the mail
server to configure an outbound mail server in order for email from
onCourse to be delivered:`#23213`
+
- SMTP username (optional)
+
- SMTP password (optional)
* You can now send templates from the following list views`#24380`
+
- waiting list
+
- invoice
+
- application
+
- payment in
+
- payment out
* Addition of new report in the class list "Enrolment summary by state".
This shows the detail of each state's running and cancelled classes, and
enrolment numbers by gender in each class
* Addition of a new class roll "Class roll – Age". This shows the
students age in years next to their mobile phone number.
* Addition of a new class roll "Class roll – USI". This shows the units
of competency covered in the class and the student's USI status – not
supplied, verified or not verified
* Update to the enrolment fee sheet in the class budget tab, in
preparation for the upcoming payment plan feature
* Update to the invoice edit view layout, in preparation for the
upcoming payment plan feature. Manual payment schedules can be created
for an existing invoice in this release, but they will not be visible to
your customers until the completed feature set is rolled out.
* With the addition of manual invoices that can be linked to a class
budget in 7.0, a number of budget reports required updates to include
this new type of income. Updates have been made to Budget Details by
Class, Budget Summary by Class and the Pre-Paid Fee Liability report
(now only available in class list, no longer in the enrolment list)

== Fixes

* Improved speed of drop down panels which were drawing in slow motion.
This was particularly noticeable for Windows users. `#23736`
* New validation message requires new record to be saved before
attempting to attach documents `#23894`
* Ensure selection of a top level tag also selects all records tagged
with any of its child tags `#23439`
* Country of Residency value was not saving when updated in the contact
record `#23942`
* Ensure contact merge retains saved values of AVETMISS enrolment
question responses `#23997`
* Quick search option in the applications window now searches by Student
Name and Course Name `#23975`
* Contact merge window has been resized so it won't be truncated on
lower resolution displays `#23696`
* Improved speed of opening the cogwheel list when a large number of
records have been selected `#23699`
* Fix to application status to ensure it is correctly marked as
'accepted' when a student enrolment is processed via Quick Enrol from an
'offered' application `#24016`
* Fix to payrate override function when two valid pay rates already
exisit for the tutor role `#24101`
* Prevent application selection from disabled courses `#23994`
* Allow payroll and payslips to contain $0.00 lines as valid values
`#24114`
* Export OSPC for overseas delivery sites and student addresses in the
AVETMISS NAT00020, NAT00080 and NAT00085 files `#24202`
* Fix to the CSV Class Export file alignment when the class is not
assigned to a site and room `#22611`
* Fix to the VET FEE HELP export files where the class census date was
incorrectly formatted `#24181`
* Remove any information about GST (inc or ex) in relation to voucher
products on the web as they are non-taxable supply `#23603`
* Ensure invoices manually joined to a class are included in the income
totals in the class budget `#24047`
* Fix display of voucher 'value available' in Quick Enrol to only show
the unused portions, excluding any amount applied to the current
enrolment `#24161`
* Customer reference field on printed invoice widened to allow for 24
characters `#23786`
* Improved credit card payment failure handling to reduce the occurrence
of enrolment stuck 'in transaction' `#18926`
* Add Quick search option to voucher window. Quick search operates on
the 'Invoice to' contact value `#24276`
* Ensure 'this record has been changed' message does not appear when
cancel is selected and no change has been made `#24025`
* Fix the AVETMISS export dialogue so it says the 'The AVETMISS files
were created in…' instead of 'The null files were created in…' `#24076`
* Allow attachments uploaded in error to be deleted before saving and
closing the record `#24192`
* Enable voucher product URLs that have not been enabled for online sale
to be accessible via direct URL for customers who have purchased them
through the office `#24196`
* Ensure email 'undeliverable' setting is only set automatically after 6
emails have attempted and failed to be delivered `#24398`
* Improve the class to room join where the rooms have all been changed
at the session level `#23926`
* Allow shared saved searches to be deleted by any onCourse user
`#24210`
* Improvement to the user interface for opening documents from within
records `#24528`
* Ensure email receipt is not sent when the checkbox is unticked
`#24566`
* Include details of all invoices payment has been applied to on emailed
payment receipt `#22297`
* Fix to enrolment cancellation process that was preventing $0
enrolments from being cancelled `#24586`
