= Release 0.6
19 Feb 2007


== Major features

=== Merge duplicate students

Sometimes students records end up being duplicated due to mistakes such
as misspelling or change of email address. Once you have found duplicate
students you can merge them, choosing fields from each record to use.

=== Compression for replication.

When sending and receiving data from your onCourse website the
transmission is now compressed usually to under 20% of the full size.
This speeds up transfers and reduces bandwidth costs.

=== Concessions and promotional codes.

Fiendish in their simplicity and power, these discounts can link back to
a saved search of students, allowing discounts to be applied to specific
categories of students. They can be percentages or dollar amounts, can
be limited in time period and apply to any range of classes you choose.

== Minor features

* Saved searches allow for any find criteria to be saved either for
personal or shared use. This might be a search such as "find all
students who have done a language course in the last 6 months" or "find
classes with less than 10 enrolments". These saved searches, no matter
how complex, can then be easily performed on the current database at any
time.
* Improved speed of printing the calendar
* Clairvoyant (type-ahead) fields now have a shortcut button allowing a
user to quickly pull up the full details of the linked data. (This is
pretty hard to explain without pictures and pointing – just try it and
see)
* Find options available now for derived data such as "show me students
who enrolled in language courses in the last 80 days".
* Improved speed of many windows opening and closing. We still have more
to do for the classes list view which is slower than we'd like it.

== Fixes

* As usual, a range of small cosmetic issues and some more obscure bugs
reported by users have been fixed. Only one reported issue remains
unfixed (related to AVETMISS outcome generation) but we added more
logging so we can track it down if it happens again.
