
= Release 121
07 Novemver 2023

We are pleased to release onCourse version 121 to all customers, which includes some minor bug fixes and one big new feature, a new class type - Hybrid Classes.

=== Major Feature
* New class type - Hybrid class

The hybrid class type is a class that offers a combination of timetabled sessions and self-paced learning. Create both timetabled sessions and set a number of self-paced study hours. Define the number of sessions a student must attend before they are considered completed.

onCourse will show a hybrid class enrolment as complete when a student is marked as attended in the number of sessions that are set to complete.

E.G. if the class requires students attend at least five sessions, the moment any student is marked as attending their fifth session, that enrolment will appear as complete in onCourse. This does not affect or change how VET certificates work - outcomes must still be marked as successfully completed before certificates can be issued.

Read more in our manual, here - https://www.ish.com.au/onCourse/doc/manual/#classes-hybrid[Hybrid Classes]

=== Minor Fixes
* Fixed an issue where you could not link relations in contact record in checkout `OD-18602`
* Improved read-only timetable filter performance `OD-18581`
* Fixed an issue where removing a discount in Checkout could throw an error `OD-18569`
* Fixed an issue where list views were losing horizontal positioning when scrolling vertically `OD-18073`


