= Release 9.6



== Important changes

When you first run onCourse 9.6, it downloads all the new application
resources as usual. Note that this release has a very large set of new
resources totalling about 190Mb so this might take some time on slower
connections. It is not expected that every future release will be this
large since it incrementally just downloads changes resources.

== Major features

onCourse now supports Java 9 and 10. You can upgrade your local
installation of Java past version 8 now, although there is no need to do
so until Java 8 is discontinued in 2019. Java 11 drops the webstart
functionality which means you'll need to install a client onCourse
application manually after each upgrade. We'll have a solution for that
in 2019, in the meantime it will be easier if you remain on Java 10.
Also note that we needed to rebuild how the attendance view in the class
edit screen scrolls horizontally to work around some Java 9 issues. This
will only impact you if you have a large number of sessions in a class.

We have also completely rebuilt the user interface for general
preferences. There are only minor functional changes as this is our
prototype of the new UI which will be progressively rolled out across
the whole application. We welcome feedback on the usability of these
changes.

The third major change in this release is a complete rebuild of the way
the server application initialises itself. Although this isn't a user
visible change, it will help us to better fine tune server caching,
memory usage and performance.

== Reports and scripts

* Fixed an error in the Course Completion Survey reports that makes the
print process fail when one or more survey responses has a blank
response. `OD-11771`
* Fixed an error where the Cancelled Class report was including records
that should be suppressed. The report data was correct, but the total
was including values from cancelled classes and running classes, where
it should have been cancelled classes only. `OD-11796`
* Fixed the plain text version of the Tax Invoice report to show the
missing Discount column. `OD-11889`
* Updated Smart and Skilled (NSW) export flavour to reflect recent
changes around reporting requirements. Please refer to Smart and Skilled
update 64 for more information. `OD-11982`

== Minor features

* Added the ability to duplicate data collection forms. `OD-10821`
* Custom fields created in onCourse Preferences can now be manually
sorted by dragging and dropping them on the page. `OD-11017`
* Added Data Collection rules for payer and parent. You can now create
separate rules for collecting data from people who are the allocated
payer or the parent on an online enrolment. `OD-11918`
* New import CSV 'onCourse contact update subscriptions CSV import'
added to onCourse. Lets you set marketing flags for contacts via CSV
import.

== Fixes

* onCourse ish blog entries are again shown in the Help menu in the nav
bar - Help > onCourse News `OD-11127`
* Fixed an issue where the transfer process was not applying contra
payments as expected. `OD-11844`
* Fixed an issue where the application could lock up when clicking
'next' in class edit view on the Budget tab. `OD-11882`
* 'Vouchers' are now a printable entity, meaning they can be printed as
a report. `OD-11890`
* Amended some logic in the AVETMISS export window that showed an
override checkbox without context. `OD-11903`
* Fixed an error where you couldn't duplicate and reverse an invoice
with an attached payment plan. `OD-11922`
* Contacts: The 'Custom fields' tab will now show in red when an error
exists within a mandatory custom field. `OD-11926`
* Fixed an error that caused the 'alert students of related class'
script to send to students who were already enrolled. `OD-11934`
* Updated override information that displays for AVETMISS export flavour
formats STSOnline and SA. `OD-11946`
* Fixed an error in the Survey Report caused when every survey related
to one of the selected classes has one or more scores set to equal 0.
`OD-11947`
* Fixed an AVETMISS 8 error where NAT00080 'Client Name for Encryption'
was incorrectly set for single name students. `OD-11950`

== Web features

* Changing the class hiding date will now change search results. That
is, if you set classes to disappear from the website 5 days before they
finish, that should change which courses are found in a search.
`OD-10279`
* 301 redirects now work with query string parameters (for example a URL
like "/about-us?source=mail" is now redirected the same way as just
"/about-us"). `OD-11923`
* Kiosk now displays the tutor for a session where that tutor is
different to the default for the class. `OD-11902`
* Remove the tutor page from the website when the tutor's employment
termination date in the past. `OD-11760`
* You can now choose to show the price for classes that are set to
'Enrol by Application'. `OD-11708`

== Web fixes

* Fixed an issue where "Near" courses searched sorts results
incorrectly. We were assigning sort weight by distance in the wrong
units which threw off some of the results. `OD-11920`
* Fixed an issue where searching for "after date before today" by URL
query threw an error. You can use a URL like /courses?after=20180820 but
previously that would only work if the date was in the future.
`OD-11842`
