
= Release 123
29 May 2023

We are pleased to announce onCourse version 123. This version of onCourse introduces a brand new SkillsOnCourse portal, rebuilt from the ground-up with modern technologies and updated security protocols. It also contains some new fixes and quality of life improvements, as well as some new features to support larger customers with multiple faculties or departments who would like to filter courses by these 'faculties'.

== Major Features

*New Portal*

* Updated user interface, built from the ground-up using modern technologies and optimised for phones as well as desktop.
* Upgraded security.
* Configure the portal to use your own logo and branded colour.
* Configure multiple portals for different corporate customers, faculties or departments, each with their own logo and colour branding.

*Faculties*

* Added a new entity in onCourse - Faculties.
* Faculties are applied to Courses. You can apply only one Faculty to a course at a time.
* Faculties can be made visible on the website and are also searchable by students. Faculty pages on the website will show the Faculty description, as set within onCourse, and a list of courses that have this Faculty set against them.

== Minor Features

* Added support for Adobe Analytics.
* Moved 'Subjects' from Tags to Preferences - this is to better highlight Subjects as a key part of your onCourse set up. The functionality remains the same.
* Added an automation to invite newly enrolled students who haven't yet created a password for the new portal to do so.
* Added a warning to scripts that are set to run against ALL records.
* Added 'Class Types' and 'Course Types' to preferences. These can be used as additional course filters on the website, though they are disabled by default.
* New hybrid class controls allow you to set when enrolled students gain and lose access to class materials.

== Minor Fixes
* Fixed an issue where Subjects could only have one tag set.
* Fixed an issue where Subjects tags couldn't be deleted from Courses.
* Fixed an issue where the Membership window would sometimes appear blank.
* Fixed an issue where some conditional logic in data collection could cause problems in checkout.
* Foxed an issue where QR codes for certificates were pointing to a broken URL instead of validating.
* Fixed an issue where some default automations were showing with no description.
