= Release 45
14 Oct. 2020

== Important changes

== Major features

=== New rich text editor

We are rolling out a new editor for rich text fields across onCourse. Based on markdown syntax it includes a preview mode and helpers for common styling. You can also select to continue using our legacy textile markup, or you can set it to HTML if you want to do things that way instead.


=== Changing course when duplicating classes

When you duplicate a class you now have the option to attach the new class to a different course. This is useful when your course content changes slightly each term but the class schedule remains largely the same.

=== Xero integration now supports payroll

The Xero integration has been substantially rewritten and now supports pushing payroll entries automatically into Xero. This could save you hours of data entry each pay cycle.


== Minor features

* Added support for different renderers in Sites web description `OD-14951`
* Outcomes three column view - added Outcome code in front of name `OD-14975`
* Hidden form fields for users when those fields are not permitted for view `OD-15081`
* Can now paste your 2FA code `OD-15225`


== Fixes
* Fixed an issue where daylight savings time was not shown in date entry helper `OD-14919`
* Fixed an issue where users were not able to add tag to group of classes if one or more classes had that tag already added `OD-15205`
* Fixed an error where a document's name was not visible in dashboard activity `OD-15214`
* Fixed issue where double-clicking the Save button was creating duplicate records `OD-15215`
* Fixed issue where the 'No value' font color was set incorrectly `OD-15223`
* Fixed a documentation error where anchors didn't scroll to the correct section `OD-15236`

== Web
* Editor now supports markdown style rich text
