= Release 45
14 Oct. 2020

== Important changes

== Major features

=== New rich text editor

We are rolling out a new editor for rich text fields across onCourse. Based on markdown syntax it includes a preview mode and helpers for common styling.


=== Changing course when duplicating classes

When you duplicate a class you now have the option to attach the new class to a different course. This is useful when you course content changes slightly each term but the class schedule remains largely the same.

=== Xero integration now supports payroll

The Xero integration has been substantially rewritten and now supports pushing payroll entries automatically into Xero. This could save you hours of data entry each pay cycle.


== Minor features

* Support renderers for sites web description `OD-14951`
* Outcomes three column view - add Outcome code in front of name `OD-14975`
* Hide form fields not permitted for view `OD-15081`
* Allow paste to work for 2FA code `OD-15225`
* Documentation anchors don't scroll to correct section `OD-15236`

== Fixes
* Daylight saving time not shown in date entry helper `OD-14919`
* Bulk tag add - not able to add tag to group of classes if one or more class has tag already added `OD-15205`
* Document names not visible on dashboard activity `OD-15214`
* Double-clicking the save button is creating duplicate records `OD-15215`
* 'No value' font color is wrong `OD-15223`

== Web
* Editor now supports markdown style rich text
