= Release 111
17 Feb 2022

== Important changes

Phone numbers have now been stripped of all non-numerical content. This 'normalisation' makes it possible to search for phone numbers in the checkout.

== Major features

=== Abandoned cart

If you are using an onCourse website, any time a user gets part way through checkout and does not complete, a record of their shopping basket will be kept against their contact record. This makes it possible to send them reminders to complete the checkout and for you to help them complete the process if necessary.

When you use the onCourse checkout, you'll be prompted to load a customer's abandoned cart if one exists. In the future, we'll add scripts to the system to send them a reminder to return to your website and complete the checkout.

=== Checkout enchancements

We've expanded the search in the Checkout. In the contact field you can type a contact's name, phone number or email address to find their contact record.

We've also enhanced the lead creation process, allowing you to create a lead from directly within the Checkout. If you add a single contact and a course (without selecting a class) to the shopping cart.

While we're on the subject of Leads, you can now use the 'convert to sale' function within the Leads cogwheel menu to send the lead to the checkout. This will populate the checkout with the contact record and the courses they expressed interest in, allowing you to quickly select classes and accept payment.

== Reports and scripts
* Optionally expand 'Historic aged debtor' report to include transaction lines `OD-17006`
* Removed Historic aged debtor script, was a duplicate with the Historic aged debtor export.
* Moved Historic aged debtor export to be run from the Contacts window.

== Minor features
* Search for a contact by name, email and phone when in the Checkout `OD-16895`
* Can create a lead from directly within Checkout `OD-16897`
* In Leads, you can now directly send a lead to the checkout with 'convert to sale' cogwheel function.  `OD-16899`
* In Contacts > Financial, added Abandoned checkout shopping carts UI showing the number of abandoned carts for that contact.  `OD-16915`

== Fixes
* Fixed an issue where the edit icon for the class fee was missing from the right sidebar `OD-16916`
* Fixed some inconsistent naming of Product entity fields in UI `OD-16928`
* Fixed an issue where in Data Collection Forms, the Save button incorrectly showed a warning icon `OD-16959`
* Fixed an issue where the Historic debtors export could miss invoices when checking on due date `OD-17007`
