= Release 9.7

== Release 9.7

=== Major features

==== New login and security screens

The entire login process (`OD-11935`) and the security preferences
(`OD-11936`) have been rebuilt using our new user interface. Users might
notice several things:

* the new design
* a reminder to set two factor authentication
* a prompt to change their password if it's considered of low quality

Although we've had two factor one-time-passwords (OTP) for about five
years, few people have used it. Yes, it's slightly less convenient, but
it does improve security by a huge amount, so onCourse will start
nagging you to turn it on at every launch. You can still ignore these
requests, but the administrator can enforce an OTP policy in the new
security settings. The administrator can also increase the threshold of
what we consider a rubbish password, forcing users to change to a better
one.

==== Special interests in data collection

With mailing lists being removed from onCourse (everyone is using more
specialised advanced tools like Mailchimp), we've repurposed the old
functionality into 'special interests' `OD-11833`. This means that you
can now add Contact tags into data collection rules and make them part
of the questions you ask during enrolment, applications or waiting
lists.

For example, you might like a set of checkboxes whenever someone adds
themselves to a waiting list

....
Other than this course, what other areas of training are you interested in:
[ ] leisure courses
[ ] languages
[ ] computer courses
            
....

Or, ask specific questions about experience, work history or profession
as part of the enrolments process. Any set of Contact tags in onCourse
can now be entered by students directly if you choose to make them part
of a Data Collection rule.

=== Reports and scripts

* Smart & Skilled reporting 85 - Not Yet Started and TNC for Did Not
Start outcome results. This has been in place since version 9.6
`OD-11982`
* Update contact CSV export to include the standard working with
children check fields `OD-11793`

==== Minor features

* Added script to send birthday gift email `OD-11746`
* Added link to manual to question mark help icon within preferences
`OD-11917`
* New generic import to change subscription to marketing materials
permissions, per user `OD-11962`
* Deprecate id methods in the DSL. You should rarely be using the record
ids directly in an onCourse script and we've now removed them from the
documentation. They will still work for now. `OD-12018`
* Certificate expiry. You can now add an expiry date to a certificate
record. Although VET certificates don't expire according to the
standard, there are many cases where other bodies require regular
recertification such as First Aid. `OD-12031`
* Add to class duplication: optionally skip copying of class tags and
class notes `OD-7475`
* Link a manual invoice to an enrolment `OD-8284`

==== Fixes

* Fixed small error that caused Special Smart & Skilled and SkillsTAS
NAT00130 rules to no longer apply `OD-11753`
* Fixed where no 'from' email address was defined in default script
'send product purchased email' `OD-11928`
* Fixed handling of single name students in AVETMISS 8 NAT00080 files
`OD-11950`
* Fixed issue where users couldn't add VET modules to course on OS X
webstart with Java 10 `OD-11997`
* Fixed the scrolling bug in Class Attendance tab `OD-12004`
* Fixed an issue where the COS account wasn't appearing in Invoice
Detail as expected `OD-12005`
* Fixed an issue where sessions information for class records were being
saved before sessions were added `OD-12014`
* Fixed an issue where the Attendance screen didn't line up `OD-12042`
* Fixed an issue where users could no longer mark Attendance by the
column `OD-12043`

==== Web features

* The Google Maps implementation has been reworked to load less often,
reducing traffic and cost to the google map servers.
