[[webstart]]
== onCourse set up

If you install onCourse yourself, rather than using the managed service from ish, you'll need to configure the environment into which you install onCourse. You will need:

* A unix, linux, OSX or Windows operating system
* A database. No database specific features are used, but onCourse is regularly tested with MariaDB, MySQL, and Amazon Aurora RDS. Others like postgresql or SQL Server might also work, but aren't regularly tested.
* An outbound mail server (smtp)
* Java 11 or higher

=== Installing dependencies

On MacOS, use homebrew to install many of the requirements.

1. https://brew.sh/[Install homebrew.]
1. Install MariaDB 10.4. `brew install mariadb@10.4`
1. Install Java. ` brew tap homebrew/cask-versions; brew install temurin11`

Now set up your database.

1. `brew services start mariadb` to start the server
1. `mysql_secure_installation` and configure the root account.
1. `mysql -uroot -p` to log in to the SQL console and execute some commands to create a user. Use a proper secure password instead of 'password123'.

    CREATE USER 'onCourse' IDENTIFIED BY 'password123';
    GRANT ALL PRIVILEGES ON * . * TO 'onCourse';
    FLUSH PRIVILEGES;

    CREATE DATABASE onCourse;
    exit;

[[install]]
== Installing onCourse on your server

https://www.ish.com.au/download[Download onCourse Server]. There is one application bundle which will work on OSX, Windows, Linux and Unix platforms. Unzip it to any suitable folder.

onCourse is happy in a virtualised environment such as VMWare, Xen, or AWS EC2. Ensure that you have sufficient RAM and CPU allocated. onCourse Server only writes to disk for log files, so memory and CPU are more important than disk performance. Allocate at least 400Mb of RAM, but at least 1Gb is better. onCourse will take all the memory you give it to cache data and run faster, up to a point.


[[install-oncourseyml]]
=== onCourse.yml

The bundled onCourse.yml looks like this:

[source,yaml]
----
http:
    port: 443
    ip: 127.0.0.1
    path: /

db:
    uri: 'jdbc:mariadb://127.0.0.1/onCourse?user=onCourse&password=password123'

license:
    max_concurrent_users: 99
    custom_scripts: True
    access_control: True

smtp:
    email_batch: 100000
    host: smtp.gmail.com
    port: 465
    mode: tls
    username: your_email@gmail.com
    password: your_email_password
----

At a minimum, you'll want to set the ip address to a reachable address on your server. Perhaps you'll have onCourse behind a firewall or load balancer or exposed directly to the internet on a public IP address. That's up to you. In order to run onCourse on a port lower than 1024 you will typically need to run it as root. Remember that onCourse includes functionality to write scripts which can then access the entire system as the user the server is running as, so where possible run onCourse as a non-privileged user or run it in a jail.

The database connection should be configured appropriately. The mariadb JDBC driver should work fine with mysql or AWS Aurora, but if you want to use Microsoft SQL server you'll need to add the jtds library to your classpath.

The license section allows you to limit concurrent users and disable some functionality of the product. The smtp mode can be one of:

* tls
* starttls
* unsafe

Use 'unsafe' only if you are sure you want to send unencrypted mail across your network or the internet. That's usually a bad thing. If you want to use gmail to send outbound mail, you'll need to provide a valid username and password here, and also https://myaccount.google.com/lesssecureapps[relax security settings here]. Otherwise you can use your ISP's mail server, your office server or an MTA like exim you install locally.

=== Invite new users

To create the first user or to reset passwords if you have lost them, create a file called `createAdminUsers.txt` and put it in the same folder as onCourse.yml. That file should contain one line per user in the format:

----
firstName lastName email
----

Put spaces between the fields. When you restart onCourse this file will be deleted and those users will be sent an invite link by email.



[[install-sslcert]]
=== SSL Certificate

Then you'll need to create a certificate for your browser to connect to onCourse with. For testing you can use a self-signed certificate, but in production you'll definitely need a properly signed certificate for your domain. First create a PEM formatted certificate and key pair named "onCourseSSL.pem", complete with all intermediate certificates.

[source,shell script]
----
openssl genrsa -aes256 -out onCourseSSL.key 4096
----

Enter any password at the prompt.

[source,shell script]
----
openssl req -new -x509 -key onCourseSSL.key -out onCourseSSL.pem -days 825
----

Answer all the questions. The Common Name should be the fully qualified domain name of the onCourse Server you are deploying. At this point you should get this key signed by Let's Encrypt or another certifying authority. Then continue converting the certificate and key to pkcs12 and then to a keystore:

[source,shell script]
----
openssl pkcs12 -export -out onCourseSSL.pkcs12 -in onCourseSSL.pem -inkey onCourseSSL.key -password pass:ish2008

keytool -v -importkeystore -srckeystore onCourseSSL.pkcs12 -srcstoretype PKCS12 -destkeystore onCourseSSL.keystore -deststoretype PKCS12 -srcstorepass ish2008 -deststorepass ish2008 -noprompt
----

`keytool` comes bundled with the Java JDK. The final result is a file called onCourseSSL.keystore which you should put in the same directory as onCourse.yml.

[[install-serverLaunch]]
=== Launching server

Run onCourse using either the `bin/server.bat` Windows script file or `bin/server` for all other platforms.

Once it is running, you should be able to connect with your browser. Make sure you use https, any special port you've chosen and your browser will need to support HTTP/2.


[[advancedSetup-serverMemory]]
=== Memory allocation

Edit the value of `DEFAULT_JVM_OPTS` in the bin/server or bin/server.bat. The parameter `-Xmx` specifies the largest amount of heap memory allocated to the application. Java will allocate a bit more than this for compiling code and running the JVM itself. It is very important that you don't allocate more memory than the machine actually has available or else everything will run incredibly slowly as the operating system swaps to disk.

More memory generally helps onCourse run faster.

=== Log files

onCourse will create a `logSetup.xml` file in the same directory as `onCourse.yml` when it starts up. This is a standard log4j2 configuration file and you have full access to all the configuration of how logs are output, rolled over and the logging levels.

By default logs are output to a folder called 'logs' in the same directory as the application.

=== Upgrading onCourse

Shut down the server and replace all the application files. It is important to completely delete the old lib folder and remove old files; don't just keeping adding the new ones. Really the only file you need to keep between releases is onCourse.yml.
