= Release 1.7



== Major features

=== Private Booking

This function allows users within the Quick Enrol screen to create a
custom class with a room, tutor and cost assigned and then enrol one or
more students. You could use this feature to create a private class for
a corporate client, to deliver a personalised training program to an
individual or small group, or to create a 1-on-1 coaching session. The
class can have one or more sessions, with the maximum enrolment set to
the number of student(s) you enrol at the time of creation. Once
scheduled, the class will be recorded within the database just like your
other classes, with enrolments created and entries in the timetables for
your students, room and tutors recorded.

=== Scheduling collision detection for resources

Double booked rooms and tutors have warning icons appear next to them on
the Calendar view. You can drag and drop the session within the calendar
to a different time, that doesn't conflict with another booking. or you
can keep the session double booked, for example if you want to purposely
book two classes into a room in case one is cancelled. Along with the
Private Booking feature, this would greatly suit our users who often
arrange small private sessions.

=== Improved relationship options in Quick Enrol

When using Quick Enrol there are a number of options available to take
advantage of relationships.

You can set a relationship between contacts and the payer of the
enrolment at the time of enrolment. This is useful when enrolling
friends together or a when a parent pays for a child's tuition.

If existing relationships have already been set for contacts, we take
advantage of this when adding contacts in Quick Enrol.

As example if you add a contact that is a parent, the child(ren) will
appear as an option when clicking on the "+" icon when choosing to add
an additional contact.

=== Increased speed over the internet

We have optimised the communication between client and server to much it
much faster over slow links (eg. when using onCourse over an internet
link). This, combined with our SSL encryption of the channel, makes
onCourse very usable across multiple sites and even wireless links.

=== XML Export

Throughout almost all list views in onCourse a new export feature allows
the user to export raw XML data, or data transformed into a wide range
of possible options. Because we chose the XSLT technology as a way of
transforming the export data, users are able to write their own
transforms. You can use an XSL stylesheet to export data as pdf, Word,
csv, tab delimited or almost any other data format you can imagine.

=== Server configuration file

Allows some useful parameters to be specified for the server such as
database location, IP address(es) and ports to listen on. This file will
allow onCourse to be more easily customised for those who have unusual
requirements on their network when the usual onCourse defaults don't
quite fit.

Our service installer will now detect the location of the configuration
file and not prompt for a database location.

=== Refunds

Refund credit cards though payment gateway, making it much easier to
cancel classes and refund students without having to phone the student
to get their card details.

=== Full list

* Credit card refunds
* Budget report
* Timetable clashes
* In calendar sessions which collide with double booked Tutor or Room
are shown with an icon. Validation runs when you open a calendar or move
a session.
* Add predefined fields to SMS and email: Allow and to be used in
SMS/email messages
* Quick enrol accepts course-class codes to improve easy lookup of
classes
* Remove all tags from this tag group, Right clicking on the list of
tags in window will allow the user to select "Remove all tags from this
tag group"
* Improved room selection
* Class mailing list report renamed to "Mailing list export" when
choosing to print in class list window
* Invoice a company (or any contact), not just students
* Improve logging for Windows, rolling over a daily log
* Improvements to 3rd Party Payment tracking: Enrolments have a icon
that links to invoice to identify payer
* Export all table data to flat files
* Allow contact delivery options checkboxes to be searchable (post and
email, deliverable, opt out of marketing etc)
* More search options for course/class
** Classes
*** number enrolled
*** Qualification code
*** Unit of competency code
** Courses
*** with classes currently on offer/ with no classes currently on offer
*** query by the course "currently offered flag"
* Windows problem with file dialog: Resolved a problem where choosing an
alternate folder would delete the filename
* Payments in: Send tax invoice with paid notification, when creating a
new payment on the payment in screen there is a tickbox to email the
payer with a tax invoice
* All date fields now render with day of the week in list views on mouse
hover. ie. Mon or Tue will appear
* Indicate if field is too small to display the data it contains: if
information is larger than the field there is an … icon to indicate
there is more data
* List prefetching implemented: greatly improves performance when client
and server are not on the same network or remote
* Printing improvements to Certificate of Attendance
* "Lost Connection" dialog cannot be closed.
* Class tutor list report includes class name
* Improved the ability to add and select tutors when a pool of tutors is
available for a class
* Concession validation
* Server config file: when "onCourse.cfg" file is present in the same
directory as the onCourseServer exe. This will allow the setting of
port, ssl_port, database location, and IP addresses to listen on.
* Allow attachments to be linked to Sites
* Server shows error to user when unable to start, rather than silently
failing
* Year is visible on date picker: when using the date picker, the year
can be selected in the popup
* Fixed list views not updating after enrolments added
* The goto contact icon is send message works correctly
* Include web address (if website enabled) for enrolment confirmations
* Improve payment functionality: Payments can be marked agsinst specific
invoices rather than automatically selected against the oldest.
* XSLT based export
* On windows ctrl click to multiple select in class list is same as
right click
* Improved image/pdf attachment
* Green colour coding on Class list screen to show when minimum is
reached
* User not able to exit Student -> Financial tab -> Payment-in sheet:
certain combination of access rights prevented exit out of payment in
* Hide RTO features via preferences checkbox
* Private class booking facility
** Access via quick enrol via "+" button
** Allow users within the Quick Enrol screen to create a custom class
that has a room, tutor and cost assigned and then enrol one or more
students
** You can duplicate an existing class or create a brand new class
* VET funding report errors
* Outcomes for students whose enrolments are cancelled shouldn't be
visible
* When the server detects an attempt to downgrade the database the user
will see an appropriate message
* Improve relationship options: more options available for relationships
such as parent, sibling, child, friend etc.
* Payment tracking full amount in Quick Enrol: add preference "[ ] Quick
Enrol payment defaults to $0" and if the user already changed the
payment amount from the full amount to something else this remains
unchanged
* Quick Enrol: improved visibility of delete button
* Email invoice improvements
* Bug in date fields of advanced find
* Quick Enrol: Use relationships to select additional contacts
* Quick Enrol: Suggest relationships for contacts
* Fixed Payment AmountPrevious owing and Balance outstanding not
recalculating correctly on the Quick Enrol screen.
* Duplicate class sheet date field made wider to avoid being partially
obscurred by calendar icon
* User can create an enrolment without access to do so
* User can change tags when they don't have access
* Include year in date of birth on "student contact list" report feature
request
* Fixed a problem when attaching a pdf
* Course AVETMISS validation problem
* Add sessions dialog — pre-populate room: if the class has a room
defined this will be in the session dialog
* Attempting to kick out user from the server GUI now works as expected
* Status not set correctly on certain paymentOuts
* Fixed validation on disabled fields is not shown.
* HTML email url does not honor system web proxy
* onCourse data population via webservice only: this reduces the first
startup time of the server
* Long email addresses is not longer chopped in Student contact list
report.
* Multiple concessions for each Discount
* Changes to statements of attainments report
