= Release 115
18 May. 2022

== Major features

=== Timetable upgrades

We're upgrading the Timetable view in onCourse, giving you more customisation and functionality to allow it to work better for your work situation.

==== Heatmap

The new heatmap appears in the monthly calendar widget in the top-left of the timetable view, giving you an at-a-glance view of how packed your days are relative to the others. The darker the colour, the more you have going on in that day. The colours are worked out relative to the busiest day versus the least busy day in terms of classes.

==== Groupings

You can now group the timetable days into days per tutor, days per room, or no grouping (which is just the normal day by day calendar view). This lets you get a better view of each day per tutor or room, letting you better plan the coming days, weeks and months worth of upcoming classes.

==== Tags in timetable

You can now turn off the tags in the timetable view, as well use either the full tag view, or the collapsed tag view.

=== Tags UI Update

We've updated the UI in Tags to make it easier to drag and drop your tags into the correct tag structure.

=== Checkout queries

Add any course, class or product from your system directly into a student's web cart automatically using specific queries on the end of the /checkout URL. For example, you can now directly email a checkout link to a student, and when they click it, all the specified items will already be added to their cart. They just need to complete the checkout process.

This opens up many, many possibilities, especially around accessbility for users who struggle with computers, as well as making it easier to bundle items together into one checkout using a single link.

== Minor features
* Updated age restriction wording in Classes to offer better understanding of how it works `OD-17199`
* Re-labelled two timetable buttons in contacts to specify between student timetable and tutor timetable `OD-17167`
* Timetable queries will now show in the onCourse URL. The search bar has been removed as it was redundant `OD-17165`
* Added 'Timetable' to Find Related search in the following screens: class, course, site and room `OD-14567`
* Added 'Student timetable' and 'Tutor timetable' to Find related search in contacts `OD-14567`

== Fixes
* Fixed an issue where plugin scripts weren't showing when expected `OD-17243`
* Fixed an issue where users weren't able to click on the on a contact name in Latest Activity `OD-17236`
* Fixed an issue that could cause some documents to not open correctly `OD-17205`
* Fixed an issue with the headerbackground colour when using Monochrome theme `OD-16657`

