= Release 114
11 Apr. 2022

== Major features

=== Contact insights

In our quest to enhance onCourse's CRM features, we've introduced the contact insights panel.

Now when you search for a contact from the main menu, or click one of the new hand wavy links on a contact through the system, you'll get the new set of insights and timeline.

No longer do you need to search through 25 places to find recent notes, documents and events relating to a contact. Instead, it's all nicely collated in one spot.


== Minor features
* You can now add system user names to message templates directly using DSL `OD-16955`
* Can add a note to contact via activity timeline `OD-16997`
* Added an icon to access new contact insights panel from all relevant edit views `OD-17146`
* Admin password reset will re-enable a user if they were disabled `OD-17018`

== Fixes
* Fixed an issue that could rarely cause a custom script to not be opened `OD-17177`
* Fixed an issue where custom filters could not be saved `OD-17187`
