= Release 114
11 Apr. 2022

== Major features

=== Contact insights

In our quest to enhance onCourse's CRM features, we've introduced the contact insights panel. Now when you search for a contact from the main menu, or click one of the new hand wavy links on a contact through the system, you'll get the new set of insights and timeline.

No longer do you need to search through 25 places to find recent notes, documents and events relating to a contact. Instead, its all nicely collated in one spot.


== Reports and scripts
* 2 new reports - Shipping packing slip `OD-16904`
* Custom script - Prepare shipping script `OD-16905`

== Minor features
* Server should read onCourseSSL.pem instead of keystore `OD-15087`
* Messaging - systemUser to add sending user details in message templates `OD-16955`
* Note interaction date time `OD-16997`
* Open insights panel from all edit views `OD-17146`
* Admin password reset should enable user if they were disabled `OD-17018`

== Fixes
* Unable to open new custom script `OD-17177`
* Custom Filters cannot be saved `OD-17187`
