
= Release 120
25 May 2023

We are pleased to announce onCourse update 120, includes an upgrade from USI webservices version 4 to version 5, some minor upgrades to the functionailty of discounts, and a few bug fixes. As always we appreciate your feedback and support and remain commited to making onCourse even better to use.

=== Major Upgrades
* Upgraded all systems from USI webservices version 4 to version 5 `OD-17392`

=== Minor Features
* Reworked how discounts can be selectively displayed, now available to be selected to use for soley online enrolments `OD-18146`
* The days before an audit log is automatically deleted is now able to be changed `OD-18088`

=== Minor Fixes
* When writing descriptions using legacy text the spacebar was not adding spaces correctly `OD-18052`
* Running an AVETMISS export while using a custom date prompted an error `OD-18049`
* Waiting list bulk delete did not have a confirmation dialog `OD-18064`
* Error when creating a new invoice from the invoices window `OD-18073`
* Changed some wording involving removing related items from the checkout `OD-18084`
* Discounting a class by 100% would create a price of -$0.01 when listed online `OD-18127`
* Advanced Query Language with .tags wasn't functioning as intended `OD-17397`
