= Release 84
6 Jun. 2021

== Major features
Outcomes now show progression in a pair of graphs. This progression shows assessments and attendance.

This flows through into the AVETMISS export window, separating out outcomes which have commenced (a student has submitted some assessment) from those which have just started (the first session has happeend).

== Minor features
* Voucher underpayment can now be customised per voucher `OD-15925`
* Xero integration adjustments to meet Xero UX requirements `OD-16027`
* Outcomes edit view - new section - Progression `OD-16127`
* Add case insensitive sorting of lists in several places `OD-16151`
* Service NSW Scripts `OD-16154`
* Outcome commencement depends on assessment engagement for AVETMISS export `OD-16157`
* Some fields on vouchers should be editable even after the voucher is redeemed `OD-16172`
* SurveyGizmo renamed to Alchemer `OD-16160`

== Fixes
* Unable to add a new room to a virtual site `OD-15948`
* mailchimp/oncourse integrations mailchimp subscribe `OD-16085`
* Automation - options showing wrong information `OD-16148`
* Payment plans in checkout could auto-fill the wrong amount for previous invoices `OD-16167`
