= Release 9.8



== Major features

=== onCourse query language

`OD-12002`This release introduces the new onCourse query language in
what might be the most useful usability feature introduced to onCourse
since "Find Related". For now, this query language is available only in
the new Modules, Qualifications and Script views and will be rolled out
across the entire user interface in upcoming releases.

=== Script user interface

`OD-11969`Scripts now have a clean new user interface, allowing you to
more easily create and edit scripts for onCourse. With the new query
language integration, you can easily find records in onCourse to perform
operations on.

=== New AVETMISS export user interface

`OD-12114`The AVETMISS export process has a pretty new UI to make it
clearer and simpler to export the data you need. With more detailed
information about each step in your VET workflow, it makes it easier to
find and correct data.

=== New list and edit user interface

`OD-12203`We've rolled out the new three panel combined list/edit view
in Modules and Qualifications. This is a seldom used part of onCourse so
its a good place to show off what we've done without introducing major
changes right at the end of the year. Even if you aren't an RTO take a
look at these new screens and play with the search and column selection
options. We want your feedback as we continue to roll this UI across the
entire application.

== Minor features

* Certificate expiry date`OD-12031`. Certificates can be given an expiry
date which is useful for courses like first aid.
* The new user interface has been applied to managing tags.`OD-12105`
* Bundle Java 11 inside the standalone client application.`OD-12137`
* Fix incorrect display of non-$ currency symbol in PDF and
CSV`OD-12147`
* Login screen adjustments`OD-12195`. When running the standalone client
application, you can now specify the server host as a single word. Port
now defaults to 443.
* Remove Avetmiss 6 export`OD-12201`. The time has come to remove some
old export code no one needs any more.
* Self-updating client app`OD-12204`
