= Release 71
18 Mar. 2021

== Major features

=== Assessment submissions

An entirely new part of onCourse has been introduced, allowing you to store and mark student submissions against assessments. This is not yet integrated with the portal, but that will come soon.

=== API tokens

To make it much easier to authenticate external services to the onCourse API we've introduced API tokens. You can create secure keys to allow external access to the API without worrying about a login and cookie handshake.

== Reports and scripts

== Minor features
* A Save button is now available in discard changes dialog `OD-12525`
* Split class discounts into Promo Discounts and Related Discounts section on class budget UI `OD-15480`
* Added a discount drop-down box to Invoice record view. `OD-15503`
* Ui Changes in Outcomes make overridden and calculated dates more obvious `OD-15667`
* Added 'find related' links between certificates and outcomes `OD-15684`
* Moved some Student Loan fields from Class to Course `OD-15686`
* Updated error message that shows when user attempts to upload document that already exists in system `OD-15704`
* Added a default 'no-reply' from email address for when no default from address exists `OD-15718`

== Fixes
* Fixed an issue where voucher types web description field was in old style `OD-15327`
* We now sort the room list in a site record by A-Z `OD-15578`
* Fixed an issue where Canvas script was not creating enrolments in Canvas `OD-15611`
* Fixed an issue where upload document dialog appeared intermittently `OD-15701`
* Fixed an issue where Mailchimp scripts weren't creating/updating new contacts `OD-15581`
* Fixed an issue where some headings in rich text editor menu selection did not match actual rich text applied `OD-15691`
