= Release 2.0



== Major features

=== Memberships and Discounts

Memberships are a new type of product which is available to sell to
customers. Memberships can be created within onCourse for individuals or
groups or related contacts, such as employees of a company. A membership
can have one or more discounts attached, allowing special class prices
to be made available to membership holders. Memberships can expire a set
period of days after their purchase. This is the first of many products
we plan on implementing within onCourse over the coming versions. The
Promotional Code and Concessions windows have now been merged into a
single window called Discounts.

=== Dashboard Update

The onCourse dashboard has been redesigned to represent the main areas
of business and process of our users. The new tabbed approach allows us
to offer more options to users to access onCourse functions. The
dashboard is now grouped into "Course Setup", "Customer Service",
"Accounts" and "Marketing" and additional explanation text is provided
to assist new users in navigating their way through the software.

=== Timetable and Resource Availability

The major revision of the class window layout includes significant
improvements to the timetabling and scheduling functions in onCourse.
Proposed sessions allow you to see at a glance any scheduling conflicts
before you finalise a classes sessions. New unavailability tools for
tutors, rooms, sites and the college allow you to create entries when
these resources are not available for class bookings due to outside
bookings, public holidays or for any other reason. New timetable views
and editing options allow you to see eight weeks at a glance and edit
all, or a single session of a class. The class window list now shows a
session count. Creating timetabled sessions are now essential for a
class to have a start and end date.

=== Attendance and CRICOS

Attendance marking for scheduled sessions is available for both tutors
and students. Attendance can be marked from within the onCourse
application or via the web tutor portal. Records of student absence and
partial attendance can be recorded, and percentage of attendance is
calculated. Of particular benefit to CRICOS colleges, students with less
than 80% and less than 70% attendance are flagged within the system for
follow up. Additional recording fields for student VISA and OSHC have
been added to the student AVETMISS tab for use with CRICOS students.

=== Tutor Pay Rates

Found under File -> Preferences -> Tutor Role. For each tutor role you
create, you can add multiple pay rates. When a tutor is assigned to the
class, the default pay rate of their tutor type will apply via the
budget, assisting you in calculating the direct costs of running the
class. This function can also be used to calculate 'per enrolment
payments' to other staff members, like the class coordinator or an
external contractor. Tutor attendance at scheduled sessions can be
confirmed and pay cards created for your chosen pay periods, calculating
the total gross income due to the tutor, ready to submit to your payroll
department.

=== Improvements to Class Window

The layout of the class window has changed to better reflect the
workflow of setting up classes for enrolment and managing class
viability. The general tab now shows summary information of the class,
which is set in other tabs in the record making it easier for users to
see at a glance the status of the class. In combination with the
improvements to the budget feature, this summary will calculate the
class viability based on the number of current and projected enrolments
from the class costs you have assigned. The class fee (how much the
student has to pay on enrolment) has moved to the budget tab, to
facilitate future development allowing deposit fees, charges for
additional class resources like textbooks or catering, and fees payable
by other contacts, like employers, to be added in future versions.

== Reports and scripts

=== New Reports

==== Transaction detail and Transaction summary

From Accounts > Print > Transaction Detail > select date range

The single Profit and Loss report available from the Accounts print menu
now has two options – summary and detail, which can be printed for your
chosen date range

==== Room Details

From Rooms > Print > Room Details > select date range

This report will print all sessions scheduled in a room for the
specified date range, showing booked times, tutor and number of students

==== All class details Report

From Classes> Print > All class details

Will print all the information you have set up for the class including
number of students currently enrolled, various fees available for
enrolment, course, class, tutor and session descriptions.

==== Class roll – Contact no

From Classes > Print > Class roll – contact no

Will print the class roll with the student's mobile phone number

==== Class roll – single session

From classes > Print > Class Roll – single session

A roll listing all the students names, designed to be passed around and
signed for a single session only.

==== onCourse sales report

From enrolments > Print > Sales report

A report listing the total volume of sales processed by each onCourse
user, grouped by their location

==== Annual enrolment comparison

From enrolments > Print > Enrolment annual comparison

Shows the number of enrolments processed each day plus a cumulative
enrolment count for the year, in comparison to the previous year

==== Assessment Outcome Report

From Classes > Print > Assessment outcome report

Creates a grid of the units assigned in the course and the students
enrolled in the class so the assessor can record their outcome results

== Minor features

=== Attachment Improvements

Previous versions of onCourse required you to attach a document each
time you wanted to reference within a course description. You can now
reference existing file attachments as well as adding new attachments.
This means you only keep one Attachment with one name.

=== Change to Quick Enrol

The email or print enrolment confirmation process is now an action you
perform at the end of the enrolment. No more forgetting to set email or
print while taking enrolment details.

=== Reports and Email Templates

Moved from General Preferences to File -> Preferences -> Report list.
Reports can now be added in bulk and minor edits made from within the
user interface. Email templates have moved from General Preferences to
File -> Preferences -> Email template list.
