
= Release 118
6 Oct. 2022

With this 118 release of onCourse we continue to fix issues and add small quality of life improvements across the board, including some improvements to PDF backgrounds, the ability to bulk edit outcome override dates, a brand new integration and some more goodies.

There are also numerous fixes and improvements to the user interface, that will hopefully allow for smoother navigation and flow throughout the onCourse application.

=== Minor features

* Added the ability to create transactions via scripts `OD-17492`
* PDF Backgrounds can now be downloaded as PNG files. `OD-17468`
* The PDF Backgrounds window now features enhanced previews `OD-17468`
* PDF Backgrounds can now be uploaded in a variety of formats, including .jpg, .tif and .png files `OD-17468`
* Added the ability to bulk edit outcome start and end override dates `OD-17427`
* Added the ability for find anything search on the dashboard to look for middle names. `OD-17389`
* Added a new parameter to Contacts that can be called in export and reports called totalInvoiced - shows to the total value in $ invoiced to the contact `OD-17403`
* Added a new integration for Kronos systems. With this integration you can send your tutor session rosters directly to your Kronos Workforce Ready system. `OD-17266`
* Added the ability to add an item to Favourites directly from find anything search `OD-17161`
* Added a new Voucher email template that clearly displays the remaining value and their voucher code `OD-17055`

=== Fixes and Improvements

* Fixed an issue where invoices could show an owing amount if more than one payment type was used in Checkout `OD-17496`
* Fixed an issue where users were incorrectly asked to save or discard changes when navigating from a record via the global navigation `OD-17487`
* Fixed some spelling errors in the global navigation column `OD-17482`
* Fixed an incorrect description for the script block in Automations `OD-17460`
* Fixed an issue where completed checklists were appearing in the timetable as a tag `OD-17458`
* Fixed an issue where you can't remove Sites from a lead `OD-17384`
* Fixed an issue where enabling some columns in list view could cause the window to crash and be upopenable again for that user `OD-17361`
* Fixed a number of small UI issues `OD-16804`
* Increased the amount of time it take for web checkout to timeout based on feedback from Windcave. This will hopefully resolve any issues experienced by people who leave the checkout sitting dormant for a few minutes or more `OD-17371`
* Increased readability of nested lists in contacts `OD-17073`
* Class attendance and assessment submissions are now all ordered alphabetically to help with readability `OD-15965`
* Small improvements to default contact merging controls `OD-13369`