= Release 113
19 Mar. 2022

== Major features

=== New navigation

The primary navigation has been reworked to add more explanatory text for each option and group them in categories. The goal is to make onCourse more discoverable for new users and to showcase the different functionality it makes available.

=== New automation view

All the automation windows have been updated with a new more informative view. Gone is the clutter of a thousand scripts in the left sidebar and instead there is a new library style view with descriptions of the actions you might like to add.

Install any number of automations from the library, and then enable or disable them as you please.

=== Set up tutorial for new systems

When starting up a brand new onCourse system, we now show a series of panels on the dashboard to guide new users through the important steps for getting started.

== Reports and scripts
* Remove class cancelled print report which was faulty and add new columns to the class budget export to show cancelled enrolments and total credits given  `OD-17091`
* Default export for contact in json format `OD-17098`

== Minor features
* Automation category titles should be clickable `OD-17102`
* Store onCourse ids in Canvas `OD-17048`
* Suspend/Unsuspend the student’s Canvas account upon completion `OD-17049`
* Canvas store student password `OD-17050`
* Canvas create a course from a blueprint `OD-17051`
* Canvas add tutor `OD-17052`
* Canvas student attributes `OD-17078`
* Hide XML export features in UI when there is no permission in the security settings `OD-12464`
* Server will read onCourseSSL.pem instead of keystore `OD-15087`
* Added some additional search paths to simplify query syntax `OD-16734`
* Now allow user to automatically send user name in message templates `OD-16955`

== Fixes
* Fixed spelling error in Assessments section of Class `OD-17061`
* Fixed an issue with enrolment transfers `OD-17076`
* Fixed an issue where the document shareable link would not be versioned when it shouldn't be `OD-17081`
* Removed additional validation that was constraining saving new tags with certain characters `OD-17082`
* Fixed an issue where disabled automations were not greyed out `OD-17092`
* Fixed an issue where search query for find related from messages to contact didn't work `OD-17093`
* Fixed issue in checkout where couldn't search for company name that starts with a number `OD-17094`
* Fixed an issue where Automation name field lost focus after typing one character `OD-17100`
* Removed all descriptions from PDF Backgrounds `OD-17101`
* Fixed an issue where built-in automations were always added to the library `OD-17103`
* Fixed issue where MYOB Integration couldn't be added `OD-17140`
* Admin password reset will now also activate user `OD-17018`
* Fixed an issue where working query expressions show as invalid in Automation until its in focus `OD-17122`
* Fixed an issue where user could not set new 'date banked' when creating new 'deposit banking' entry `OD-17147`
* Fixed a script cog wheel rendering problem `OD-17163`
* Fixed an issue where the script alert tutors of assessment release query is not working `OD-17172`
* Fixed an issue that stopped users from openning a new custom script `OD-17177`
