= Release 7.2
22 May 2015


== Major features

=== Payment plans

A new concept for enrolment fee payments has been developed to allow for
online enrolments by paying a deposit, and regular payments thereafter.

Payment plans consist of scripts which can be applied to classes en
masse, and plans in individual classes with payment dates and amounts
which can be modified as required.

The student fee window in the class has changed to allow for more
options in creating and setting a class fee with a deposit and then
additional amounts payable in relation to the class start date.

During enrolment, the default option of payment of a payment plan class
is for the deposit component only, but additional amounts up to the full
class fee can be taken at this time.

Any discount that applies to an enrolment will be deducted from the
final payment amount.

The invoice window layout has also had significant change to clean up
the view and accommodate the payment plan schedule. Within the payment
plan invoice, payable amounts and due dates can be adjusted, added or
removed, for the individual student. Any invoice can be manually turned
into a payment plan invoice if the balance was not paid in full on
enrolment.

The printed invoice template has also been updated to include the
payment plan schedule of dates and amounts payable, as have the email
templates.

When a student has an invoice with payment plan amounts due in the
future, and they enrol in another course, the future payable components
will not be added to their amount payable in Quick Enrol. Only overdue
payment amounts will be automatically added.

A new access right has been created for payment plans. Ensure you update
your access roles to allow the appropriate permissions for your staff to
create and edit payment plans within both classes and invoices.

== Reports and scripts

When a change has been made to a script or template, onCourse will not
automatically overwrite your files as you may have added your own
customisations. You can choose to update your templates and scripts
manually by accessing the latest versions on GitHub.

* Wording in the default Voucher purchase plain text and HTML template
was made consistent, with the word 'quick' removed from the HTML voucher
template.
* Labels for tax amounts updated in the plain text Tax Invoice. Total is
now shown inclusive of tax, and tax is itemized separately.
* Payment plan payment dates and amounts payable have also been added to
the Tax Invoice plain text and HTML templates. The link for the item
above is directly to the plain text template which includes these
changes.
* An optional clause can be added to the student and tutor reminder
scripts to only send to classes that have met their minimum enrolment
requirements – if ( courseClass.successAndQueuedEnrolments.size() >=
courseClass.minimumPlaces ) \{.

== Minor features

* Add find related invoices from products window cog wheel `#24215`
* Add find related payslips from classes window cog wheel `#24508`
* Add 'last login' date to users list view, to assist with finding users
who no longer log in to onCourse regularly `#24475`
* Change the discount default option to 'classes tagged with' to avoid
users accidentally selecting all classes `#24319`
* Improve voucher redemption process in Quick Enrol to show the voucher
redemption balance available and to edit the value being redeemed as
part of this purchase `#24130`

== Fixes

* For find related 'contacts purchased' from product find contacts with
successful purchases, and exclude contacts with failed purchase attempts
`#24211`
* For the advanced search option in contacts 'number of enrolments' only
count active enrolments, and exclude failed, cancelled or credited
enrolments `#24504`
* Quick Enrol window layout was adjusted so relationships window was
better accessible as it was sometimes drawn off screen `#22983`
* Ensure outcomes tab correctly updates UOC when the course code is
changed to another course after class creation. The course code can not
be changed for a class once the class has enrolments `#23570`
* Display payment out amounts in banking with a negative symbol in front
of the the amount `#24015`
* Improvement to the certification creation logic from the class cog
wheel. In summary: When a course is 'sufficient for qualification' a
qualification is created for student where all outcomes have been
successfully achieved, a Statement of Attainment when some of outcomes
are successful and some unsuccessful, and no certificate is created when
all outcomes are unsuccessful. When a course is NOT 'sufficient for
qualification', a Statement of Attainment is created when at least one
outcome was successful, and no certificate is created when all outcomes
are unsuccessful. `#24223`
* Improvement to the labeling and identification of failed payment
attempts on the invoice payment summary `#24781`
