= Release 7.10

== Release 7.10

=== Major features

==== 3rd Party Integration preferences

A new window to create integration preferences has been added to
onCourse for the following popular commercial tools:

https://moodle.org/[Moodle] – A free, open-source PHP web application
for producing modular internet-based courses that support a modern
social constructionist pedagogy

http://mailchimp.com/[Mailchimp] – Online email marketing solution to
manage contacts, send emails and track results

https://www.surveymonkey.com/[SurveyMonkey] – Create and publish online
surveys in minutes, and view the results graphically in real time.
SurveyMonkey provides free online questionnaire and survey software

https://www.surveygizmo.com/[SurveyGizmo] – An exceptionally powerful
survey tool designed to make even the most advanced survey projects fun,
easy and affordable

These integrations allow you to create your own links to external
services and products you have purchased, and define with a
corresponding script how onCourse utilises these services.

==== New preferences windows

All onCourse preferences settings have been moved into a single window
with a more intuitive layout. Under File > Preferences > General… you'll
find all the general preferences previously available (College,
Licences, Messaging, Class Defaults, LDAP, Maintenance & AVETMISS).

Financial general preferences has been merged into this window and a new
preference has been created for adding Holidays (unavailabilities) for
your whole of business timetable and scheduling availability.

=== Reports and scripts

* A new Certificate template has been added for Skills Sets. `#24920`
* Class details report sorts in chronological order by default `#25624`
* Add capacity to define the name of the export file inside a script
`#25654`

=== Minor features

*Sales improvements*

* People > Purchased memberships list view has had additional columns
and core filters added to the window to make it more readable and
sortable `#25246`
* A new edit purchased membership view has been added to the Purchased
Memberships and Sales windows. When you double click on a membership
that has been purchased you can change the expiry date and view the
enrolments it has been used for `#25249`
* Date purchased column added to Sales window `#25787`
* 'Delivered' status and cog wheel function to set status to delivered
added to product sales and products filter in Sales window `#25788`

*Other improvements*

* Add to invoice advanced search options the invoice line description
`#21185`
* Add onCourse student number to user choice of retention/replacement
options in the contact merge feature `#22694`
* Suppress the send credit note email option and send cancellation
message option when using the enrolment transfer wizard `#25398`
* Pre-populate Quick Enrol with the course from the transferred
enrolment, along with the payer and student details `#25398`
* For new users, all windows open by default to 65% of their screen
size, until they adjust their own layout and preference settings
`#25704`

=== Fixes

* When cycling through enrolment records using the 'next' and 'previous'
option, the VET Fee Help fee charged value updates to show the current
record value as expected `#25343`
* VET Fee Help charged value automatically calculates to be inclusive of
any discounts or tax applied to the enrolment fee `#25513`
* Improvement to the Class Budgets CSV export to make the values
exported consistent with the values displayed in the class budget view
`#25384`
* When creating a new manual tutor payslip, only allow clairvoyant
lookup of contacts marked as tutors `#25489`
* Invoice manual payment plan view row height increased to make values
readable during edit `#25512`
* CONTRA payments now display on the contact financial record summary to
calculate the correct totals when a payment is reversed `#25526`
* Time limitations on credit card payments out have been removed
`#13396`
* A range of advanced search fixes to remove any instances of case
sensitivity `#25674`
* Fix to the cancel voucher UI to allow a cancellation fee to be charged
`#25790`
* Exclude any outcomes with Outcome Status – National 'Did not start –
66' from AVETMISS exporting except in NSW Department of Education and
NSW Smart and Skilled export flavours `#25549`
