= Release 75
7 Apr. 2021

== Minor features
* Implemented Course-module relation rules for checkout `OD-15458`
* Can now 'copy' text from all fields `OD-15685`
* Tests for components of preferences concession-types `OD-15791`
* Tests for components of preferences contact-relation-types `OD-15792`
* Tests for components of preferences custom-fields `OD-15793`
* Tests for components of preferences data-collection-forms `OD-15801`
* Tests for components of preferences data-collection-rules `OD-15802`
* Added a new NSW Creative kids integration `OD-15851`
* Added bulk tagging to Assessments, Applications, Tutor pay, Waiting Lists, Rooms and Sites `OD-15804`

== Fixes
* Fixed an issue where Prior Learning dates couldn't be added and records couldn't be saved `OD-15810`
* Fixed issue where classes 3-column view was showing 'save/discard' message when not needed `OD-15813`
* Fixed issue where, when creating manual certificate, 'Level' field didn't update until save `OD-15815`
* Fixed error that could show in Outcomes for some users `OD-15825`
* Fixed an issue where setting due date when 'Pay Now' = $0 wasn't creating an invoice due on the right date `OD-15827`

== Web fixes
* Fixed support for IE11 in checkout `OD-15774`

