= Release 2.1.4

== Release 2.1.4

=== Reports and scripts

Improvement to the class cog wheel 'create certificates' function
allowing you to create a mix of VET and non-VET certificates in a single
action

=== Fixes

* Some problems were introduced in 2.1.2 which prevented some parts of
the onCourse Web from being updated after changes in onCourse. This is
now fixed.
* In an attempt to fix the advanced search on tags, 2.1.3 broke search
on subject tags in the class list view. This is now fixed. Searching on
more than one tag at once in the advanced search still has problems and
the fix is targeted for 2.1.5 in the next few weeks. This issue has
proven more complex than we hoped.
* Some users running MS-SQL and MySQL back end databases had troubled
upgrading past 2.1.1. This fixes the problem.

==== Minor fixes

* Advanced find fixed for 'Tagged with'
* Advanced find fixed for 'Number of enrolments' (note this includes
cancelled and credited enrolments)
* Advanced find fixed for SMS, Email & Post searches for 'accepted and
can be delivered'
* Fix to QE process where sometimes contacts defined as companies could
not be selected
