= Release 53
24 Nov. 2020

== Major features

=== Sellable item relationships

Course and product relationships now have user definable types with a number of configurable properties for marketing purposes. This feature will allow you to set relationships between both courses and products that will affect how these items are sold.

They can have specific shopping cart actions such as:

. suggestion only - these items will appear as suggestions in the cart/checkout

==== co-requisite

Items with this relationship are added to the cart/checkout automatically. They can be locked to the cart, or removable.

[start=2]
. add to cart and allow removal
. add to cart and don't allow removal

==== pre-requisite

Items with this relationship are added to the cart/checkout automatically, but only if the user has never purchased/enrolled in them before. They can be locked to the cart, or removable.

[start=4]
. add to cart and allow removal
. add to cart and don't allow removal

== Minor features
* Remove 'endsWith' from AQL for richtext fields since the new richtext mode will break these searches  `OD-14952`
* Remove system resources which have been removed from the application `OD-15230`
* Increase the image preview size in document cards and make it easier to update sharing permissions `OD-15307`
