= Release 93
12 Aug. 2021

== Important changes

== Major features

=== Leads

A new concept has been added to onCourse to enhance the CRM functionality. Leads represent a relationship between a contact (person or company) and zero or more products or courses. In this way you can track prospects and leads right from first contact or even just a mailing list through to conversion into a sale.


=== Quotes

You can also now create quotes, which are just like invoices except you can edit them right until they are sent to the customer. If accepted, they can be really easily converted into an invoice.

Typically, you would attach quotes to a lead in order to track the progression of the sales process.



== Minor features
* Scripts now allow multi-line content in a message block `OD-16332`
* Remove a number of internal Java classes and interfaces which are no longer used `OD-16015`
* Remove ldap and budget licenses. Everyone gets these features now! `OD-16196`
* Payslip - add pay type column to list view `OD-16329`
* Show "Shared with website visitors" flag for documents attached to contact records `OD-16352`
* Hide reversed payments from deposit banking list `OD-16368`

== Fixes
* Fixed issue where if a tutor was added to a class in more than one role, the tutor was shown twice as an assessment assessor in submissions `OD-16244`
* Fixed an issue where 'Enrol highlighted student' option in Waiting Lists didn't work correctly `OD-16325`
* For discounts which require more than one enrolment, make sure all enrolments are in the discount class list rather than just one `OD-16317`
