= Release 8.7



== Major features

=== Discount override at the class level

This new feature allows you to override the discount value at the class
level, to assign varying class fees sharing the same discount name. This
option may be especially useful for funded programs like Smart &
Skilled. For example, a number of courses and classes can share the
discount 'First Qualification rate' but each class can have it's own
discounted price. Double click on the discount in the class budget tab
to edit it.

=== Discount offset from class start date

In addition to discounts running for a set date period, discounts can
now be set to be valid as an offset from the class start date. The
offset can allow the discount to run prior to the start date, or after
the start date. This will allow the creation of both early bird style
pricing and discounts for in-term enrolments.

=== Prior learning edit and export

Prior learning data imported into onCourse now has its own view in the
contact education tab. These records can be double clicked to edit, and
new records can be added manually. All prior learning data added
manually or via import will also be collected and exported in whole of
college date range AVETMISS reporting.

== Reports and scripts

* A new OLGR data export file was added to the contact window for
customers delivering RSA training `#26609`
* Two new management reports added to the class window - Enrolment
Income by Account and Enrolment Summary by Account. These reports show
the enrolment numbers and income invoiced for classes selected in the
report, grouped by income codes. The summary report shows only a total
for each income account, without the class by class data `#26748`
* Make it easier to send links to specific portal pages like this
restrictedPortalURL("class" + $\{cc.willowId}, 7) which creates a link
to the class page with an expiry of 7 days. This is particularly helpful
for survey invites. `#26583`

== Minor features

* Add check box option to retain or remove class VET data during
duplication. Data is retained by default `#26606`
* Renamed the enrolment tab in the contact window to education to
reflect the addition of prior learning `#26768`
* Add + button to the contact window on the education tab above the
enrolment panel to open Quick Enrol with the student's details
pre-populated `#26768`
* Added search index for invoice dates and source to run faster queries
against these fields in onCourse `#26869`
* Redesign the front page of the class edit view to better present
discounts, including the customised discount values. `#27123`
* Added access level role to the user list view `#26797`

== Fixes

* Under certain circumstances, heavy use of scripts would exhaust all
the server memory preventing any further logins `#27219`
* Classes without any sessions, but not marked as self-paced would cause
problems with setting outcome dates `#27215`
* Add warning message when trying to delete a tutor with a wage that has
already created paylines `#26885`
* Honorific was incorrectly exported in position of contact title in
standard CSV export. This has been corrected, and the honorific field
added to export after the contact name `#26609`
* Country of Birth name was not exporting the expected name value in the
standard CSV exported `#26609`
* Prevent tutor middle names from displaying in web advertising copy
`#26741`
