
= Release 122
18 January 2023

We are pleased to release onCourse version 122 to all customers which includes some bug fixes, including a reworking of how tutor pay is generated, and some new quality of life features as well.

=== Minor Features

* Added the ability to bulk delete student feedback from within onCourse
* Added field inheritance to specific enrolment and outcome fields when a bulk edit is completed. `OD-18645`


=== Minor Fixes
* Fixed an issue where tutor pay was interrupting regular system operation, sometimes freezing and crashing the system. This is now fixed.
* Improved searchability of custom fields, particularly date and dateTime type fields `OD-18464`
* Fixed an issue where users were unable to upload a new or amended PDF report `OD-18499`
* Fixed an issue where list views were losing horizontal positioning when scrolling vertically `OD-18073`

== V122.4175 updates
5th February 2024

This small update features some minor changes to the product-related dashboard links, a new version of the Class Timetable Report - Planning PDF report and a small change to how an AVETMISS-related field in Enrolments exports during the AVETMISS Export process. It also includes some work towards some soon-to-be-released new features.

=== Minor Features

* Changed the name of 'Sold Items' to 'Sales'. Displays all sold products (products, memberships and vouchers).
* New dashboard selections; Sold Products, Sold Memberships, Sold Vouchers. Will open to the 'Sales' window with the Products, Memberships or Vouchers filter active by default, depending on your selection.
* AVETMISS Reporting - updated behaviour of the enrolment field 'fee exemption/concession type' field. If you set the field as OS, it will always export in the NAT00120, regardless of the flavour or other settings.

=== Minor Fixes

* Amended Waiting List message template description to reflect the fact that it cannot be sent manually.
* Added an amended Class Timetable Report - Planning PDF report that adds a page break between each class.