= Release 18



== Important changes

When viewing an outcome in detail view, you'll now see a list of any
associated AVETMISS uploads the outcome is attached to. You'll see the
date the export was run, who it was run by and the status of the
outcome.

You can now log in with your email address. The old username also works,
but email address is preferred and is what people expect from
applications these days. Check that your email address is properly
configured in security settings.

== Major features

The following windows have been migrated to the new user interface:

* Documents
* Assessments
* Change password

For users of onCourse in a web browser, we've improved the way the back
and forward buttons on work without losing any search or filtering
information. This also means you've be able to save windows as bookmarks
in your browser and to share those links with colleagues. When creating
support tickets with ish, please send us the URL of the window you are
looking at.

== Reports and scripts

* Fixed an error where demographic report ignores selection of records
`OD-14144`

== Minor features

* Add documents search on dashboard `OD-12684`
* Removed unneeded scroll bar in Share on Mac OS `OD-13562`
* Animated dragging columns `OD-13934`
* Added left sidebar navigation to additional pages like Automation
`OD-14018`
* Email marketing in new contact now set as accepted by default
`OD-14125`
* Tutors list view: non-active tutors now appear greyed out `OD-14134`

== Fixes

* Security settings: "Require 2fa every ... hours" now works in browser
instead of asking every time. `OD-14000`
* Added error messaging around outcome deletion when attached to
successful AVETMISS export `OD-14014`
* Can now search for @ in email `OD-14136`
* Find Related from Invoices to Classes now works `OD-14138`
* Gmail now renders new lines in custom messages `OD-14139`
* Notes were not duplicating to new classes `OD-14140`
* New notes now add at the top
+
OD-14142
* Can now remove site from session `OD-14159`
* Fixed course page not rendering data in new UI `OD-14165`
* Fixed enrolment status appeared differently between old and new UI
`OD-14166`
* Fixed certificate couldn't print using outcome from prior learning
`OD-14179`
