= Release 95
26 Aug. 2021

== Major features

=== Tag colours

We now show tag colours in the list and edit views. In addition, you can drag and drop the tag groups in the left sidebar of the list view in order to put your most used tags at the top. The first three tag colours are shown for each record in the list, so use drag and drop to ensure the tag colours you want to appear are at the top.

Don't forget you can change all the tag colours to suit your needs.


== Minor features
* Added sortable tag groups in list view `OD-16384`
* Added colour dots for tag edit views `OD-16385`
* Tag colours down display in list views `OD-16386`
* Added explicit button to recalculate Leads 'Estimated value' `OD-16409`

== Fixes
* Fixed an issue where class roll report was not showing students `OD-16413`
* Fixed an issue where default course completion survey was failing `OD-16426`
* Removed the overdue field from Quotes `OD-16408`
* Fixed an issue where scripts an at the wrong times to set cron `OD-16411`
* Fixed an issue where find related invoices was not working `OD-16412`
* Fixed an error where discounts for multiple enrolments in a set of courses were not applying when all students were in the same class `OD-16414`
