= Release 95
26 Aug. 2021

== Major features

=== Tag colours

We now show tag colours in the list and edit views. In addition, you can drag and drop the tag groups in the left sidebar of the list view in order to put your most used tags at the top. The first three tag colours are shown for each record in the list, so use drag and drop to ensure the tag colours you want to appear are at the top.

Don't forget you can change all the tag colours to suit your needs.


== Minor features
* Sortable tag groups in list view `OD-16384`
* Colour dots for tag edit views `OD-16385`
* Tag colour for list views `OD-16386`
* Explicit button to recalculate Leads 'Estimated value' `OD-16409`

== Fixes
* Class roll report not showing students `OD-16413`
* Default course completion survey is failing `OD-16426`
* Quotes - Overdue field still showing `OD-16408`
* Scripts running in the wrong timezone `OD-16411`
* Find related invoices is not working `OD-16412`
* Discount for multiple enrolments in a set of courses not applying when all students in the same class `OD-16414`
