= Release 7.8



== Important changes

Java 8 is now a minimum requirement to run onCourse. If your
organisation is not able to upgrade to Java 8, please contact us before
performing this upgrade.

== Major features

=== Custom field drop down boxes for onCourse and the web

Custom fields for contact records can now be made into drop down
selections of choices for use inside both the onCourse application and
on your onCourse enrolment website. This feature allows you to define a
list of choices inside the custom field settings, separating each item
with a ; e.g. Radio; TV; Internet; *

If you include an asterisk (*) in the list as per the example above,
then your users will also have the option to type in free text as a
response. You can also log into your onCourse CMS to make these custom
fields, show or be a mandatory question as part of the online enrolment,
waitlist or mailing list process.

=== Re-styled all reports

All standard reports have been reformatted for a more consistent look
and feel, and to simplify the templates for custom changes.

=== Rebuild of all onCourse exports

All export CSV, XML and other custom templates have been migrated to
Groovy. This significantly reduces the load on your server when running
large data sets for export, and allows for much simpler custom export
editing.

== Reports and scripts

* A new script (send enrolment notice for tutors) and accompanying email
template (enrolment notification) has been developed to send automatic
notifications of enrolment to a defined tutor contact for all classes
tagged with 'notify manager'. You can create a tutor role called 'course
manager' and the tutor assigned to the class with this role will receive
the notification. This script is disabled by default. `#21733`
* A new event type 'enrolment successful' has been added to the onCourse
scripting engine and can be used to trigger custom scripts `#25199`
* All new exports can now be called from, scheduled and emailed from
within a script `#25470`
* The statement report now shows and opening and closing balance for the
report time period selected `#22853`

== Minor features

* Payroll number has been added to the contact advanced search options
`#21464`
* Find related courses has been added to the class cogwheel options
`#25321`
* The default sort order of the invoice window is ascending date order,
so the newest invoices show at the top of the list `#17724`
* A 'Duplicate invoice' option has been added to the invoice cog wheel.
This allows you to quickly re-create invoices from a previous invoice
template, but change contact, change the value or add a negative symbol
for a credit note `#17723`
* Payment out credit card reversal options only show payments that are
valid to reverse e.g. those greater than the amount you wish to refund,
and those less than three months old `#13396`
* Qualification name added to the certificate list display in the
contact window `#17391`
* The class cancellation process has been optimised to make it run
faster `#21186`
* The class duplication process has been moved to the server to make it
run faster `#24958`
* A new messages list view has been added to the 'People' menu option,
showing all messages sent from onCourse. This is the same information
that is available in the contact message window, and includes all
messages sent automatically via script triggers `#24912`
* Find related contacts, invoices, membership product and enrolments has
been added to the memberships window `#25247`

== Fixes

* Improvements were made to the 'find related' options for vouchers so
that find related invoice finds invoices created on voucher purchase
(including $0 invoices) and any invoices created on voucher redemption,
and find related enrolment finds any enrolment purchases where the
voucher was used as a payment method `#25237`
* Fix to allow two tutor records to be merged successfully `#25298`
* Allow banking of inactive payment method types `#25587`
* Improvements made to the payment replication process between onCourse
and the web to reduce the occurrence records stuck in 'in transaction'
state `#24905`
