= Release 8.4

== Release 8.4

=== Major features

==== New types of discounts

Two new bulk purchase discount types were added to onCourse. One option
allows you to define discounts based on the number of enrolments in the
transaction e.g. enrol 2 people and each get 5% off, or buy one get one
free.

The second option allows you to define a discount based on the total
value of the invoice, e.g. a 10% discount applies when the total invoice
value is over $1000.

Corporate passes can now also be linked directly to discounts, so
employers or agents enrolling students can have access to a special
price.

Discounts can now also be for a negative amount i.e. the discount raises
the class fee instead of lowering it. If an enrolment is eligible for
multiple types of discounts, and one of these discounts raises the class
fee, that discount will be selected by default.

In the case where an enrolment is eligible for multiple types of
discounts that reduce the class fee, as always, the best price for the
enrolling student will be selected by default.

With the new addition of these more complicated types of discounts, the
option to 'combine discounts' has now been removed from onCourse.

==== Rewrite of the import feature

onCourse imports have been re-written in a groovy syntax, making them
easier for users to edit and extend. The most commonly used import, the
AVETMISS 80 & 85 allows you to customise the student contact data import
using AVETMISS files generated by another student management system.

==== onCourse font change

The onCourse system font has been changed to SourceSansPro to allow for
clearer display on Retina and other high resolution screens.

==== Prior Learning data

To extend upon the exisiting AVETMISS data import option in onCourse
that was used to create student records, the NAT0060 and NAT00120 files
can also be imported to creating prior learning records in onCourse.
This allows for simple migration from another AVETMISS compliant student
management systems. The prior learning table can also be used to add
enrolment and outcome data to exisiting students inside onCourse, where
learning has taken place externally to the onCourse system.

These records are visible in the contact enrolment tab 'outcomes' list,
like other outcomes the student obtains via onCourse enrolments.

==== Payroll Improvements

Tutors can now be attached to classes with multiple roles and payrates,
allowing you to assign the same contact, for example, as both a tutor
with an hourly payrate and an assessor with a per enrolment pay rate.
Per session pay rates now display the correct pay value in the class
budget, depending on the number of sessions the tutor is assigned to,
rather than multiplying the rate by the total number of sessions in the
class.

The payslip edit view layout has been rebuilt to better group and
display line items and make the editing processes, where class defaults
are overridden, clearer by displaying variations with red text. A
cogwheel option has been added next to each pay line item, replacing the
cross/delete icon, allowing you to 'defer to next pay run' to improve
the clarity of what this function does.

When you choose to defer a pay line, it will be removed from the pay
slip total for the current period, but when the payroll is generated for
the following pay period, it will appear again on that payslip. This
will continue until the pay line is processed via a pay slip.

==== Payment In & Quick Enrol redesign for payment processing

Creating a payment separately from an enrolment process used to open a
'payment in' window. The window that opens now is Quick Enrol.
Validation has been removed from inside Quick Enrol requiring the
transaction to contain at least one purchase.

Now, you can use Quick Enrol to process payments against invoices with
outstanding balances. You can do this via the normal Quick Enrol window,
or when clicking on the plus option inside the payment in list view.
This change in user interface also introduces the opportunity for
vouchers to be used as payment method after the enrolment process.

==== Preference user interface updates

The preference settings for payment types, custom fields, contact
relations and concession types have been moved from being their own menu
item and windows, to being added to the list of preference options in
the File > Preferences > General list view.

==== AVETMISS improvements

A new 'suppress for AVETMISS' field has been added to the enrolment
record. This will let users met the NSW Smart & Skilled reporting
requirements of reporting and retaining records of a deferred or
discontinued student once, and then suppress the data from reporting in
subsequent monthly reports without needing to cancel the enrolment in
onCourse.

The AVETMISS export runner default has also been changed to
automatically tick and select the option 'Export 90 for VET outcomes
which are not set'. This can still be changed to export another value,
and won't affect the rules that govern the export of two blank spaces
for NSW Smart & Skilled or 70 for outcomes completing in the following
calendar year.

=== Reports and scripts

* Improvement to date references used within the Tax Invoice email
templates. We recommend you update the date fields in your template as
per the latest version on Git Hub. `#25971`
+
If you would prefer not to overwrite the full invoice template and
remove other modifications you have made, please replace in the plain
text version of the template
+
....
Invoice created on: ${invoice.createdOn.format("d/M/yy")}
....
+
with
+
....
Invoice created on: ${invoice.invoiceDate.format("d/M/yy")}
....
+
and in the HTML version replace
+
....
${invoice.createdOn.format("EEEEE d MMMMM yyyy")}
            
....
+
with
+
....
${invoice.invoiceDate.format("EEEEE d MMMMM yyyy")}
            
....
* A new export called 'Extended outcome CSV export' was added to the
class window. It creates an excel file that looks similar to an AVETMISS
NAT00120 file, but includes additional data referencing the student name
and onCourse course and class names and codes.
* Grouping and display of costs and budget items improved in the 'Budget
summary by class' report `#25391`
* Improvement to the contact CSV export layout to include all available
onCourse fields `#25900`
* A new trigger type was created that can be used to execute scripts:
class cancelled `#26272`
* Improvement to the Outcome Assessment Report to sort by student last
name `#26404`

=== Minor features

* All discounts are now allowed to be negative (i.e. a surcharge) in
both discount schemes and manual discounts. This means the increased fee
is part of the enrolment invoice line, so the full fee charged will be
reversed should the enrolment be cancelled `#25447`
* Allow purchased memberships and products to be cancelled and an
optional credit note provided on cancellation `#25807`
* Payslips are now taggable `#25815`
* Added validation message if a tutor added to a class has an end date
in the past `#17775`
* New fields for recording Working with Children Check (WWCC) number,
expiry date, status and check date to the tutor tab of a tutor record
`#26006`
* Moved the creation of email messages to the onCourse server. This has
greatly improved the speed of sending large numbers of emails `#20489`
* AusPost suburb and postcode datafile added to onCourse, to improve
accuracy of address data entry `#22533`
* Show a message in the payment window when the payment attempt fails
and the window stays open to allow for another attempt or manual refund
`#25367`
* Validation added to ensure an outcome end date set manually can not be
before the outcome start date `#25521`
* Added date and time of document creation to the documents window.
Documents are shown sorted in chronological order by default, with the
newest documents at the top of the list `#25621`
* Added contact middle name to the AVETMISS data export files `#25783`
* Descriptions and other rich text content can now be added to the root
tag e.g. subjects so that tag content will display for the URL
www.mycollege.name/courses `#23330`
* Allow the purchase of pre-defined products when using a corporatePass
`#19808`
* The VET Fee-Help 'Type of attendance' field has been added to the
enrolment record. This allows you to set a 'Type of attendance' i.e.
full time at the class level, but change it to part time for some
students enrolled in the class `#25034`
* Remember and return by default to the last browsed location when
uploading a new document to onCourse `#25465`

=== Fixes

* Fix to the class duplication process which could sometimes fail when
tutor attendance was marked but not approved `#26023`
* Validation message added when adding contact headshot to ensure the
contact record has been saved to the database first `#25972`
* Automatically tick the 'VET' flag of a course when a unit of
competency is added to the VET tab `#25973`
* Fix to classes that were duplicated over a daylight savings change
period to show the correct time for each session `#26157`
* Label in Quick Enrol 'concession type' changed to 'Discount type' to
improve clarity of meaning `#26183`
* A technical fix was implemented to prevent a race condition in the
replication process which could leave some enrolments in an 'in
transaction' state where there were multiple users attempting to process
an enrolment into the last place in a class `#25706`
* A maximum width for tags names was introduced to visually truncate
long tag names attached to records and allow the tags to wrap correctly
in the window `#26226`
* Fix to the label in the class fee sheet to switch between "Total class
fee (inc GST)" and "Total class fee (no GST)" depending on the GST
option selected `#24264`
* Improvement to window view copy and paste to excel functions to ensure
date formats appear the same way in the pasted data as they did the
onCourse window `#25918`
