= Release 4.1
19 Aug 2013


== Major features

=== CorporatePass

The CorporatePass feature is designed to be used for training which is
paid for by the student's company or the client's agency, to allow the
student to enrol online without payment, and the invoice to be sent to
the nominated company representative for payment.

The CorporatePass feature is only available to users with an onCourse
enrolment website as they are only used during the online enrolment
process. As always, users of the standalone onCourse application can
create, and issue, unpaid invoices to third party payers at any time.

For more information, see the new CorporatePass chapter in the user
handbook

_Selecting the CorporatePass option for payment during online enrolment_

=== Printing backgrounds

Although you have always been able to customise the reports in onCourse,
you are now able to add your own customisations with greater ease. Just
create a PDF file with your letterhead or any other design which will
appear behind the reports. When you print a report you are then given an
option to upload that PDF and make it a background for your printed
report. Once you have done this, the background underlay is available
for all users of your onCourse system for any report.

This function is especially useful for colleges who wish to create
custom Certificates. Using the standard onCourse template and text, you
can print a certificate that also includes your logos, college details,
borders and images, and NRT and other AQF logos on the background.

You can even create a multiple page PDF. The first page will appear
behind the first page of your report and the second page will appear
behind all subsequent pages. onCourse remembers the last background you
used for each type of report and auto selects it next time you print the
report.

For more information on creating and managing print backgrounds, refer
to the updated Reports chapter in the user handbook

_A standard onCourse Qualification certificate printed with out a
background (left) and with a background applied (right)_

=== Course relations

Courses can now be linked to other courses. This allows you to create
relationships between courses such as between French level 1 and French
level 2; or perhaps to lead them from "MYOB for beginners" to
"Strategies for small businesses". On the website these relations will
be shown to students as suggestions for other courses they may be
interested in. This is a simple marketing device to encourage students
to explore the full breadth of what you have to offer even if these
choices are in other subject categories on your website.

_Related courses can be added from the Courses > Marketing tab (this tab
was previously named Web)_

=== USI and AVETMISS 7

onCourse includes the new USI (Unique Student Identifier) field and
capacity to export to the AVETMISS 7 version of the standard, in
preparation for reporting requirements which will come into place in
January 2014. We export to the AVETMISS 7 national standard, plus the
South Australia modified standard. For other states, we've taken a guess
as to what they want (and it may be almost right) however we await
formal documentation from each state for their interpretation of the
non-standard standard. http://xkcd.com/927[This summarises] the current
state of affairs.

Both the 6.1 and 7.0 AVETMISS reporting standards are currently
available within onCourse due to transitional reporting requirements.

_The USI field is located on the student contact record AVETMISS tab.
Data entered into this field will only export if AVETMISS 7.0 is chosen
as the export standard_

== Reports and scripts

* New outcomes export, allowing you to export all students and their
outcomes from a selection of classes to CSV format to confirm their
outcome status. Report available from File > Import/Export > Export
Classes > Class outcomes CSV
* New Trial Balance report, showing transactional movement in and out of
all accounts during the chosen date range period. Report available from
Financial > Summary Extracts > Trial Balance
* Include both Certificate issued and Certificate printed dates on
standard onCourse template certificates and transcripts, inclusion of
the onCourse student number on the transcript and removal of the
embedded logos now they are handled by background printing options
* Fix to the Discounts by Class report to ensure manual discounts were
included in the discount totals, improvements to the way combined
discounts are handled by the report, and to ensure non-active enrolments
are excluded from the report
* Invoice report includes customer Purchase Order details in the printed
report
* Improvement to the content of the invoice line title and description
for printed invoices – now shows the course and class code and name for
the enrolment, plus the name of any discount applied. Note this
improvement only applies to new invoices created after upgrade
* Update Total Discounts report to use a clearer layout and provide more
information about percentage take-up of discounts
* Fix to the layout of the Student Special Needs report which was
previously printing one record per page
* A fix to the total of the Class Invoice Record report to ensure the
total only takes the invoice lines relating to the class selected into
account

== Minor features

=== Performance

We have spent significant effort in this release to improve network
performance and reduce memory usage. This will impact the entire
application, but in particular the class edit screen has been a focus of
our efforts. You may not notice any difference if you were on a fast
local network, but remote connections should see significant
improvement. In some cases on a very slow link we observed open the
class edit view improve from 30 seconds to 5 seconds.

=== Tagging

Tag groups can now no longer be available to both courses and classes at
the same time. This has caused quite a lot of confusion for our users
over the years, and the use-case for such a feature is so narrow that we
figure it is time to restrict this option to what people mostly want to
achieve. Tagging classes should be a pretty rare thing anyway, and if
you have a tag group linked to both courses and classes, the class tags
will be deleted by this upgrade. In 99.99% of cases that's what you were
probably trying to do. If not, contact us before you run this upgrade.

=== Improvements

* Screen re-size capabilities for attendance window improved
* In class tutor add window, updated wording from 'add the selected new
tutor to class sessions' to 'add selected tutor to all class sessions'
to make the intent of the checkbox clearer
* Improvement to AVETMISS 80/85 student import process to avoid
validation errors
* Disable the outcome status options 52 RCC granted & 54 RCC not granted
as they are no longer valid in AVETMISS. Existing records with these
outcomes will retain their status, only new and unset outcomes can not
be set to this status.
* Improvement to the contact window financial tab to identify payments
in and out, and payment types
* Improvement to discount 'add classes' user interface, plus the new
ability to add classes based on tag group
* When processing a payment out by credit card, all previous payments in
are shown in reverse chronological order to assist with transaction
identification
* Improvement to discount window – now allows addition of classes by tag
group, plus simplification of the other 'add classes' options
* Modification of QLD AVETMISS export to allow for the reporting of new
Certificate 3 Guarantee Program, including the addition of the new QLD
specific outcome status code 65 – Superseded qualification.

== Fixes

* Fix to allow for changes to multiple session session duration, where
tutor pay could be set to null and disallow record save. 0min payable
time is now the default value when the payable time value is removed
* Fix of +/- 1c GST rounding issue for Memberships where GST applies
* Fix of field validation issue for onCourse User accounts which was
preventing changes being made to user accounts within onCourse
* Fix to restore labels to email and mobile phone fields within Quick
Enrol contact view
* Fix to the Concession Types access control option which was disabled
in the user interface and couldn't be applied to a role other than admin
* Failed credit card payment attempts made post invoice creation (e.g.
payments not made during Quick Enrol, when the invoice is created) no
longer ask the user if they want to reverse the invoice. Failed credit
card payment attempts during Quick Enrol still ask if you want to keep
or abandon the invoice.
* Fix to AVETMISS export to ensure that the fee paid (inclusive of
discounts) is reported in the Student Tuition Fee field, instead of the
full class fee
* Fix to the AVETMISS export to ensure that the 'Not stated' response
for Prior Educational Achievement is reported as a non response (@) in
the NAT00080, instead of a Yes (Y), creating a 'Miscellaneous' NAT00100
record
* Disabled the name field for the email templates, to prevent user
changes that could stop templates being sent for default events
* A fix to the training plan feature to ensure units removed at the
course level (when allowed, prior to any enrolment) are also removed in
the class training plan
