= Release 3.0.1

== Release 3.0.1

=== Reports and scripts

* Class roll – single session didn't excluded cancelled students.
Corrected to only print enrolments which are active.
* Fixed total on Class Invoice Record report to equal sum of column
instead of class fee x total enrolments
* Updated all Budget Reports (Budget Details by Class, Budget Details by
Subject, Budget Summary by Subject, Budget Summary by Class) to match
layout and details of updated onCourse class budget feature.
* Fixed pagination for Transaction Summary, Waiting List Report, Class
Funding Report, Class Hours, Class Tutor list, Payment In, Debtors and
Creditors Report, Discounts by Class to correct single line per page
printing
* Fixed missing content for report Student Special Needs

=== Fixes

* Improvements to the backup process to ensure only one backup is
running each day
* Fix to the saved search function to ensure correct results are
returned in subsequent searches
* No longer attempts to send confirmation emails or invoices from Quick
Enrol when email preferences have not been set
