= Release 108
18 Nov 2021

== Major features

=== Rostering overrides

You can now override the start and end time per tutor within the class timetable. That means that one tutor might arrive at a different time to another and at a different time to the scheduled class times. You'll not be able to more easily roster tutors for additional setup time, or have an assistant come in for just part of a class.

=== Edit view design update

Significant work has been done on the edit views to make them easier to read and less cluttered. We hope you enjoy the changes.


== Minor features
* Links to contact from message creation view `OD-16554`
* Rostering UI for session component  `OD-16579`
* TutorAttendance start/end date fields `OD-16583`
* Remove Session.payableDuration field `OD-16586`
* Use tutor roster for clash validation `OD-16587`
* Combine Session and Tutor attendance models  `OD-16656`
* Adjust custom resources to use tutor rostering fields instead of session dates `OD-16662`
* Point versions. From this release you'll see the version as 108.2603 rather than just 108. This will make it easier to see which releases are purely bug fixes and which introduce new features.
