= Release 0.5

== Release 0.5

=== Major features

==== Printing

This very flexible printing structure allows printing to pdf, Excel and
paper. The Excel output is a early form of data export for onCourse
(further options will be made available in the future). Because the
reporting templates are XML based, it is possible for users to customise
existing reports or created completely new reports by simply adding the
appropriate XML template files to the report setup.

=== Minor features

* Payments-out for processing refunds.
* Programmer errors (in the unlikely event that one slips through!) now
result in a special window appearing to the end user with debug
information and a button which allows the user to automatically send
that report back to ish. No confidential information is sent and all
information sent to ish may be viewed before sending. This has proved
very useful in our beta testing process, so we decided to keep this in
the final release, just in case.
* Better use of the cache on the client in order to improve speed,
particularly over slow network connections.
* Official releases of Solaris, FreeBSD and Linux builds for the server.
Even though they have been available for a little while now, we now
include them in our official build list.
* Complete reworking of server starting and stopping code, resulting in
faster startup and better handling of different quit conditions on
various platforms.
* Calendar view for sites and rooms
* Improved date parser so that tricky date entry formats, such as "today
-3w"(today minus three weeks) work better
* Improved validation of data entry in many places (eg. stripping
trailing spaces off most text fields after entry)
* Cleanup of GUI to improve usability in many places
