
= Release 117
26 July. 2022

This latest release of onCourse adds some small quality of life improvements, as well as a number of bug fixes. Some highlights include the removal of a link between 'Country of Birth' and 'Indigenous status' in the AVETMISS 8 Export, the addition of a 'Printed Certificate' column in the Outcomes list view, and some improved performance when editing records with lots of data in them.

=== Minor features

* Improved performance when updating records with lots of data associated with them `OD-17212`
* In the AVETMISS 8 Export, Indigneous status is no longer affected by the student's country of birth, as per NCVER guidelines `OD-17355`
* The validation from the field 'Level' in Qualification records has been removed. `OD-14722`
* Added a new column available for use in the Outcomes list view, called 'Printed Certificate'. This simply shows whether the outcome is attached to at least one printed, non-revoked certificate or not. If it does, the column will show 'Yes', otherwise it will be empty. `OD-14203`
* Added the ability to use 'checklist task checked' and 'checklist complete' as automation triggers


=== Fixes

* Fixed an issue where documents would sometimes show the 'discard changes' message after first upload `OD-17370`
* Fixed an issue where changing the session start time wouldn't adjust the session end time and tutor roster correctly `OD-17369`
* Fixed an issue where saving a Qualification sometimes wouldn't update record save state `OD-17357`
* Fixed an issue that could cause tagging AQL requests to not find records `OD-17352`
* Fixed an issue where documents that were attached to a course and had the 'show in portal' switch 'off' would show in the portal. These documents no longer show in the portal, as expected. `OD-17339`
* Fixed an issue where the calendar could open to a different date in browsers that aren't Google Chrome `OD-17336`
* Fixed an issue where the calendar date picker wasn't working in the Calendar view `OD-17334`
* Fixed an issue that could cause a list view to stop working for some users if they tried adding certain columns `OD-17317`
* Fixed an issue where sorting by classes by session could cause problems in the classes list view `OD-17316`
* Fixed an issue where the intermediate certificate for the server wasn't properly generated on system startupo/restart `OD-17292`
* Fixed an issue that would stop the Canvas integration from configuring correctly
* Fixed an issue around timings displayed in the contact insights panel
* Fixed an issue where transferred enrolment details weren't correctly passed to the checkout when transferring an enrolment `OD-17423`
* Fixed an issue where the find related menu would stick open for Firefox users `OD-17420`
* Fixed an issue where the entity name field was accidentally set as required in automation scripts `OD-17414`
* Fixed a UI issue that could occur when editing some fields in the contact view. `OD-17412`


== New in Release 117.3151
19th August 2022

=== Minor Features

* Added a new abandoned cart reminder email `OD-16973`
* Added method to show percentage of attendance for students per enrolment `OD-17338`
* Time now shows in Date Time column in Messages list view `OD-17394`
* Optimised how Notes work. The tick has been removed so yo now simply need to just add your note and then hit Save. There will be a very short period after hitting Enter on your note where the screen will refresh before you can hit Save. This is the server validation completing and it should be more than fast enough to not interfere with your workflow. `OD-17422`
* Removed the warning that shows up when exporting individual classes and enrolments for AVETMISS. `OD-17424`

=== Fixes

* Fixed an issue where cancelling an enrolment would cause the checkout to open in a new tab as though the student was transferring `OD-17455`
* Separated tutor and student timetable links for contacts that re classed as both types. `OD-17298`
* Fixed gender search auto-select options. They now display correctly again. `OD-17330`
* Fixed issue where it looked like you could delete a parent tag from the tag menu. Parent tags can only be deleted from the cogwheel menu. `OD-17430`
* Fixed an issue where the tutor payable duration did not update when session duration was updated via the bulk edit tools. `OD-17439`
* Fixed an issue that could cause the Batch Payments In 'Processing' button to get stuck `OD-17442`
* Further UI optimisations to the improve responsiveness when clicking in and out of different fields. `OD-17446`

== New in Release 117.3170
1st September 2022

=== Minor Features

* Added students email to the contact section in the contact overview page `OD-17463`
* Improvements to merging involving how 'no marketing' is determined `OD-17359`

=== Fixes

* Fixed an issue relating to user counts when sending messages `OD-17477`
* Fixed a graphical issue involving the adding of tags to a document `OD-17470`
*