[[javascript]]
= Javascript

== File structure

Log into webDAV and look at the folder `/s/js/`.

In there you'll see a number of javascript files which drive your onCourse website.
Some are third party vendor supplied files and others are default parts of onCourse itself. site.js is the starting point and it has a list of all the other files which are included.
Note that the order of including files can sometimes be important.
Let's look at base.js now:

[source,javascript]
----
//= minify off
//= require base.js
//= require extra.js
----

This is telling you that minification is disabled and that the javascript files base.js and extra.js are included.
This is a different syntax to SCSS so don't get them confused.
The combined output file is called all.js and the files which are merged don't need to start with an underscore.

=== Minification

Unlike CSS, the javascript is not automatically minified.
This is because sometimes javascript minification can actually break your javascript (particularly if it contains errors).
Browsers will often manage to figure out your broken javascript, but once minified, errors really cause problems.

You can enable minification by changing the "off" to "on" and saving the file.
Wait about 30 seconds and then review your site in staging before pushing it to live.

We use the Google Closure compiler to verify and minify the output.

=== Compression

all.js.gz is automatically created and used by browsers.
This is another reason minification may not be quite so important: compression often does a pretty good job of reducing the file sizes.

== Core libraries

We supply a number of third party javascript libraries with your site by default.
The following list are bundled together as dynamic.js and cannot be removed without breaking some key shopping basket functionality on the site:

* classnames
* react
* react-dom
* react-redux
* redux
* redux-thunk
* jquery 3.x

In addition there are some useful libraries which are often used when building sites:

* BxSlider 4.x
* jquery.customSelect
* jQuery Validation Plugin

You may wish to remove or add more libraries for your particular design

== config.js

config.js controls the location of the checkout pages on your site. You can relocate checkout to anywhere you'd like.

[source,javascript]
----
var checkout_config = {
  "checkoutPath": "/checkout"
}
----

checkoutPath::
The path on which your checkout page lives.
You can point this to any page on your site, as long as you create that page in the editor and add the correct markup for the checkout engine to be displayed.

[source,html]
----
<div data-cid="checkout" id="oncourse-checkout"/>
----

