[[websiteSetup]]

== Website setup

By going to the Website Setup section in onCourse, you can manage and control much of the setup behind your website, including the adding of custom domains, set up of google tag manager and analytics, and even create brand new websites from scratch.

=== Billing

The billing section will show you your current level of onCourse plan, and the number of concurrent users your licence allows for.

If you wish to make a change, click the Change button, then enter the number of concurrent users you require and select a new plan from the drop-down list. Hit cancel if you've made a mistake and don't wish to change anything.

You can also set the email address and name of the person who should be receiving invoices for your onCourse account. You can also add an invoice reference, should you require one.

Once you're happy with your changes, hit Save.

====
IMPORTANT - If you drop to a lower tier plan, it will take effect at the start of the next month. If you raise up to a higher tier plan, the change will be immediate.
====

=== Websites

Here you will see a list of all of your onCourse websites, each with four different sub-sections beneath them; analytics, URLs, tag manager and google search.

You can also create a new website. by clicking the + button next to the Websites header.

==== Creating a new website

Create a new website linked to your onCourse system by clicking the + button next to the Websites header.

When setting up a new website, you'll be asked for a website page title prefix (a page title that appears at the top of the browser), a key for the site location URL, any custom site domains you might be adding (for licence holders who are allowed custom domains) and the base template, selected from our list of site templates.

Set the page title and site location, then add your custom site domains and then select a primary hostname.

Finally, select your base template from our list.

When you're done, click Save and your new website will start to build. Websites without custom domains will appear almost instantly while those with custom domains will take a little longer.

=== Google services

You can log in and connect with Google services like analytics directly from within onCourse. Click the 'Log in' button and accept the permissions to set up your services.

==== Analytics



==== URLs

Here you can see the domains in use for this website.

You can change the page title by editing the current entry, then hitting Save. Your site location is fixed and cannot be edited.

If your onCourse plan allows for them, you can also add any custom site domains to your website here. AFter you've entered the domain nam make sure you also set the primary hostname from the drop-down box, then hit Save.

==== Tag manager


==== Google search
