= Release 7.0



== Important changes

*SELFHOSTED CUSTOMERS:* Prior to upgrade, make a manual copy of your
current email template contents. Immediately after upgrade, you may need
to change the content of the new generic onCourse email templates to
re-add your own custom text. Refer to the Email Templates chapter of the
onCourse user handbook for more information. Please contact us via your
usual support channels if you require assistance.

If you have an onCourse Cloud hosted and managed solution, your custom
templates has been imported for you during the upgrade process by ish.
You may wish to review your templates after upgrade to make your own
additional changes.

== Major features

=== USI Creation and verification process

Complying with the January 1 2015 USI requirements is important for our
RTO customers, and there are a number of tools we have added to
streamline this process for you.

The new enrolment confirmation email template contains a conditional
string for VET students that explains what a USI is and why they need to
tell you theirs. This email directs them to a special onCourse portal
page (no log in required) requesting they supply their USI or go through
the process to create one.

onCourse is now integrated with the USI Web services, so once you have
received a student's USI the web services verification process will run
and mark the USI as either 'verified' or 'not verified'. For students
completing the self service portal, they will be prompted to update
their name or date of birth in onCourse if this doesn't match their
official USI data e.g. Bob may need to update his name to Robert, as per
his drivers license record.

Every Monday morning, all recently enrolled VET students who have not
supplied you with their USI will be sent an automatic reminder email on
how to complete this process and why it is important they do so. There
is a customisable email template and script that runs this process which
you can edit to meet your preferred business requirements.

A student who gives up or can not validate their USI will be flagged in
onCourse for you to follow up.

Alternatively, you may need to undertake the creation and validation
process on behalf of the student. On the student record AVETMISS tab you
will see the USI field now has an additional option next to it that says
'create a USI'. Once you enter a 10 character USI, the verification
process will run automatically in the background. If the USI verifies,
then there is nothing more for you to do. If the verification returns an
error, you can edit the non-matching data (first name, last name or date
of birth) and try again.

Additional validation has been added to assist your USI compliance. A
student in onCourse who has a verified USI can't have their first name,
last name or date of birth changed without the USI agency having the
updated change also.

As you are not allowed to issue certifications to students without a
USI, the onCourse certificate print process now includes an additional
validation check. If your certificate record was created after 1/1/2015,
it will not print unless the student has a verified USI in onCourse.
Certificates created prior to 2015 will continue to be printable without
a USI. Additional access control levels have been added to allow you to
override this print control for selected users.

More information about the USI student portal and USI verification
process can be found in the Unique Student Identifier chapter in the
user documentation.

=== New HTML and plain text email templates

All onCourse system email templates have been re-written as part of this
release in a new formatting language. System emails can have both a
plain text and HTML version, allowing you to embed your own logos, links
and layout options in the email directly.

New templates can be created at any time, and used to send automatic
emails at the time of your choice using the the workflow and scripting
engine, also part of this release.

New email templates have been added for:

* Enrolment confirmation (including a USI request for VET students)
* Tax invoice
* Payment receipt
* Refund advice
* Voucher
* USI reminder
* Student notification of class commencement
* Tutor notification of class commencement
* Enrolment application accepted
* Enrolment application received
* Enrolment application rejected
* Email header
* Email footer

More information about the new templates is in the Email templates
chapter in the user documentation.

=== Workflow and scripting

A major revision of the way onCourse sends templated emails has been
implemented to allow for a much greater breadth of functionality and
customisation for your business.

The new Scripting function also allows onCourse to become a completely
customisable tool with your business workflow engine built right into
our core product. You can create and update onCourse records on an
event, send messages to key contacts when a record is created or
changed, or automating the publishing, exporting or printing of data how
and when you require it.

These scripts have been added for all users of onCourse, but are
switched off by default. You can enable them in your database.

* Send a reminder email to students one day before their class commences
* Send a reminder email to tutors two days before their class commences
* Send a reminder email to VET students every 7 days for the next month
if they haven't supplied their USI after enrolment
* Send a receipt on the processing of a successful payment in for a
payment taken not during the enrolment process
* Send refund advice on creation of a successful payment out e.g. credit
card refund
* Send an email to a student to notify them their application has been
accepted, what their custom enrolment fee is and how they can enrol
* Send an email to a student whose application has been rejected

More ideas about how to use scripting in your business and how to create
your own scripts is in the new onCourse Scripts and Custom Workflow
chapter in the user documentation.

All onCourse license options can choose to enable or disable scripts
provided by ish. All paid license plans can commission changes to
existing scripts or request new custom scripts from ish. Customers with
Enterprise level licensing can modify and add to their own scripts to
onCourse themselves.

=== Enrolment by Application

A new way to take enrolments has been added to onCourse. Enrolment by
application allows you to add an approval process between the student
requesting a place in a class and the enrolment and payment taking
place.

By default, all current and new courses in onCourse have been set to
'Open Enrolment', located on the course general tab. When a course is
changed to 'Enrolment by application' that will change the website to
show any of the courses classes 'Enrol now' buttons to 'Apply now' and
suppress the display of the class fee. The student will then complete
the application process for their selected course/s, which are visible
to you in onCourse as a new application record in the People menu. You
can reject or approve a students application. When you approve an
application, you can optionally set a fee override which will become the
enrolment fee for that student (useful for enrolments in programs like
Smart and Skilled) and optionally set a date where the offer to enrol
expires.

Successful students will be sent a special link to the website allowing
them to enrol in the class of their choice once their application has
been approved. The link will not allow other contacts to enrol in that
class who haven't had an application approved.

More ideas about how to use application in your business is in the new
Enrolment by application chapter in the user documentation.

=== Link manual invoices and credit notes to classes

When creating an invoice or credit note manually, you can now select
within the invoice line to link the income to a particular class by
providing the course and class code.

If you select a class during this invoice creation process, the standard
fee paid fees liability and income deferral rules will apply to this
invoice.

The income (or credit) will appear in the class budget summary and the
class session rules will apply to the income, journaling it from the pre
paid fees liability account to your selected income account, as per your
selected financial preferences. When creating a manual invoice line, you
can still select an income account which may or may not be the same
income account as defined at the class level.

The layout of the class budget tab has also been adjusted to cater for
these additional income lines. We have simplified the view by hiding all
sections which have no data.

To reverse the income out of a class that was created by a manual
invoice, you can create a manual credit note linked to the same contact
and class.

=== Find related records

An exciting new way to search and locate records for reporting,
marketing and more has been added to onCourse 6.1.

In earlier versions of onCourse, the contact window cog wheel had a
'show related….' function that allowed you to find records related to a
set of contacts. This concept has been extended to every window in
onCourse, allowing you to find related records, and then perform further
searches, filters, reporting or exporting on that data set.

For example, to locate all the employers of all the students aged 18 to
25 in the last three months of VET programs to send the Employer
Satisfaction Survey to you can search for all classes with a particular
tag or use the advanced search VET course flag. Once you have those
classes, you can highlight those delivered in the last three months, and
select from the cogwheel 'Find related….' > Enrolled students. Once the
student list has opened, you can search that list of results for
students aged 18 to 25. With the reduced list of students, you can use
the cog wheel 'Find related…' to select contacts related as Employer.
From this new window, you can use the cog wheel to send a message to the
student's employers.

=== VET FEE Help Export

A new cog wheel export option has been added to the class to export the
VET FEE Help export files for your selected class or classes. This
process works similarly to an AVETMISS export, creating a range of text
files in your user home directory. These files can be uploaded to HEPCAT
for validation and lodgement.

Note VET FEE Help exports are only available for customers on
Professional or Enterprise support plans. Contact us if you would like
to upgrade your support plan to access this feature.

== Reports and scripts

Examples of and detailed information for all new reports can be found in
the onCourse documentation reports chapter

* A new report called 'Class Tutor Pay Schedule' has been added to the
classes menu. This report provides the detail of the expected payslip
lines that will be generated for all tutors attached to a class with
wages in the budget, allowing you to confirm that the correct details
have been entered at the class level prior to generating the tutor pay.
* A new report called 'Payslip report' has been added to the payslip
menu. This allows you to print the payslips for error checking prior to
exporting them to your payroll system
* A new report called 'Class Timetable – Planning' has been added to the
classes window. This is an alternate version of the class timetable
report which includes the session private notes field.
* Updated the 'Mailing list' report to include date of birth, postal
address and phone numbers
* An important fix has been applied to the 'Transaction Summary' report
available to print from both the Transaction window and Account window.
There were some instances where when large numbers of records (> 2000)
were selected prior to printing, that the reporting engine over
calculated the totals. The date selector field for the print engine is
now a date time field so you can clearly see the start and end of the
data you wish to collect. By default, the start and end date will be
12am. To print all data for the range 1/1/2014 – 31/12/2014 enter the
date range 1/1/2014 12.00am to 1/2/2014 12.00am
* A fix to the Pre-paid fees liability report to ensure the data for
each student is displayed correctly and the report sum totals the
selected records

== Minor features

* 'Add this discount when creating or duplicating classes' checkbox has
been added to the Discount edit view on the Classes tab. If you select
this checkbox, this discount will be added to all new classes on
creation and is useful for global discounts like a 10% early bird
discount, which might apply to all your programs. Selecting this option
means you don't need to return to the discount window to manually add
new classes you've created.
* Allow fractional discounts to one decimal place
* More options for depositing you banking. An editable 'Date banked'
field has been added to the Deposit Banking window. By default this will
be set to 'today' but can be changed to the date of your choice. You can
also chose to check and uncheck whole payment type groups (e.g. cash) or
just individual transactions. Unchecking a group or item will hold it
over until you run the next bank. Using this feature you can now choose
single line items like EFT/Direct deposit payments and choose to bank
them retrospectivly to the actual 'date received' into your bank
account.
* Added 'Send email' checkbox to manual invoice/credit note window. This
option is checked by default. When you create a new invoice or credit
note, and this option is selected, it will send your email template
invoice to the contact when you save and close the record.
* Added 'Set log level' and 'view logs' HELP menu function. This will
allow you locate and send supporting files to ish if you are having any
problems with your onCourse instance on your local machine.
* Added scrolling to 'add tag' option in record windows, for very long
tag lists
* Gravatar images will automatically load for contact records if the
user has a avatar linked to their email address at
https://en.gravatar.com. Gravatar images can still be overriden with
locally uploaded profile photos as per previous onCourse versions. These
images will also display in the tutor portal on the class roll for
student identification purposes.
* The generation of payroll data has been moved to the onCourse server
to make the process run significantly faster. To create payroll records,
open the 'Tutor Pay' window and use the cogwheel option 'Generate tutor
pay…'. This will pick up all unpaid sessions for all classes up until
the date you select in the window. The class cogwheel option is still in
place, but better used for generating pay for single or small groups of
classes.

== Fixes

* Remove timezone information from date of birth field when copying and
pasting contact records from the contact list view `#21937`
* On the Special Needs report, unset gender was displaying as Female.
Report fixed to show Not Stated `#22058`
* Remove label QLD only from the outcome 90 – Result Not Available, and
allow this value to export for all flavours of AVETMISS `#22308`
* Prevent users from creating multiple paylines for the same tutor, for
the same class, of the same repetition type in the class budget, which
caused an exception when the payroll was run `#21528`
* Force window close after sending class cancellation message `#21553`
* Ensure AVETMISS calculation for fee per unit when an enrolment fee is
charged is never calculated at less than $1 per unit ( `#22593`
* Fix minimum height of course brochure description field so that a
large list of classes do not collapse it to an unreadable size `#22871`
* If a class has been published to the web can not be deleted from
onCourse, but can be unpublished or cancelled to prevent enrolments
`#22298`
* Only classes with active enrolments appear in the students timetable.
Sessions from cancelled enrolments do not show. `#21468`
* Allow for PDF backgrounds with rotations `#21609`
* Prevent a tutor added to the class from being edited prior to the
class record save `#21791`
* Skip email addresses with formatting errors during batch sending
processes and notify the onCourse user of any uncontactable addresses
encountered `#22043`
* Open payslips window to front focus after running the tutor pay
process `#22336`
* Ensure onCourse system users can not have a null administration
location `#22606`
* Re-enable operator alerts in the new Quick Enrol interface `#22807`
* Remove title field from company record view in Quick Enrol `#22982`
* Ensure class export data shows class site timezone instead of server
time zone `#23031`
* Ensure rounding for invoice reversals is calculated in the same way as
invoices to avoid potential $0.01 differences `#21685`
* Don't display cancelled vouchers when the active filter is checked
`#23288`
* Update advanced search options in Users window to search for admin =
true and active = true `#23371`
* Correctly display membership fees inclusive or exclusive of GST as per
their purchase price settings `#22779`
* Correct date of birth errors that could alter entered data where
timezone differences between client and server exist `#21198`
* Ensure CMS login passwords stay in sync with LDAP password changes
`#23003`
* Improvement to the wording for failed credit card payment out
attempts. The reference to a credit note being created was removed as
there is no credit note created during the payment out process failure,
only payment in failures `#21766`
* Update calculation method for VIC AVETMISS NAT00130 course
commencement date to match NAT00120 rules `#23152`
